import { Injectable, signal, effect } from '@angular/core';

export type Lang = 'en' | 'ar';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  public currentLang = signal<Lang>((localStorage.getItem('preferredLang') as Lang) || 'en');

  constructor() {
    effect(() => {
      const lang = this.currentLang();
      localStorage.setItem('preferredLang', lang);
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = lang;

      if (lang === 'ar') {
        document.body.classList.add('rtl-mode');
        document.body.classList.remove('ltr-mode');
      } else {
        document.body.classList.add('ltr-mode');
        document.body.classList.remove('rtl-mode');
      }
    });
  }

  public setLanguage(lang: Lang): void {
    this.currentLang.set(lang);
  }

  public toggleLanguage(): void {
    this.currentLang.update(v => v === 'en' ? 'ar' : 'en');
  }

  public get isArabic(): boolean {
    return this.currentLang() === 'ar';
  }

  public translate<T>(enValue: T, arValue: T): T {
    return this.currentLang() === 'ar' ? arValue : enValue;
  }

  public instant(key: string): string {
    if (!key) return '';
    const cleanKey = key.trim();
    const trans = translations[this.currentLang()];
    return trans[cleanKey] !== undefined ? trans[cleanKey] : key;
  }
}

const translations: { [lang in Lang]: { [key: string]: string } } = {
  en: {
    // Database Specialties fixes
    'SFB': 'Family Medicine',
    'SPOFE': 'Sports Medicine',

    // Menu
    'Home Dashboard': 'Home Dashboard',
    'Clinics & Branches': 'Clinics & Branches',
    'My Appointments': 'My Appointments',
    'Medical Records (EMR)': 'Medical Records (EMR)',
    'Book Appointment': 'Book Appointment',
    'Tele-Consultations': 'Tele-Consultations',
    'My General Profile': 'My General Profile',
    'Personal Health Metrics': 'Personal Health Metrics',
    'Professional Profile': 'Professional Profile',
    'Consultation Schedule': 'Consultation Schedule',
    'My Consultations': 'My Consultations',
    'Case Rooms': 'Case Rooms',
    'Patient EMR Records': 'Patient EMR Records',
    'Availability & Slots': 'Availability & Slots',
    'Dashboard': 'Dashboard',
    'My Clinics': 'My Clinics',
    'Doctors Roster': 'Doctors Roster',
    'Global Configurations': 'Global Configurations',
    'Public Portal Home': 'Public Portal Home',
    'Logout': 'Logout',
    'View Public Portal': 'View Public Portal',
    'Dashboard Title': 'Dashboard',
    // Landing
    'Find a clinic': 'Find a clinic',
    'Platform features': 'Platform features',
    'Verified Network': 'Verified Network',
    'Go to Portal Dashboard →': 'Go to Portal Dashboard →',
    'Sign in': 'Sign in',
    'Sign up / List Clinic': 'Sign up / List Clinic',
    'MOH Eyebrow': '🇸🇦 Saudi Arabia & GCC Healthcare Portal',
    'Find a clinic.Connect with the right doctor.': 'Find a clinic. Connect with the right doctor.',
    'Search verified private clinics across Saudi Arabia. Browse doctors, filter by specialty, city, language, and availability — and book real appointments online.': 'Search verified private clinics across Saudi Arabia. Browse doctors, filter by specialty, city, language, and availability — and book real appointments online.',
    'Search clinics': 'Search clinics',
    'All Cities / Areas': '📍 All Cities / Areas',
    'Specialty:': 'Specialty:',
    'All': 'All',
    'All clinics verified by MOH': 'All clinics verified by MOH',
    'Real-time doctor schedules': 'real-time doctor schedules',
    'HIPAA-compliant system': 'HIPAA-compliant system',
    'Arabic & English': 'Arabic & English',
    'Verified Medical Clinics': 'Verified Medical Clinics',
    'Showing clinics': 'Showing clinics',
    'Sort by:': 'Sort by:',
    'Clinics List': 'Clinics List',
    'Filter Specialties': 'Filter Specialties',
    // Filters & Results
    'Filters & Refinements': 'Filters & Refinements',
    'Clear all': 'Clear all',
    'Doctor Availability': 'Doctor Availability',
    'Available Today Only': 'Available Today Only',
    'Medical Specialty': 'Medical Specialty',
    'City Location': 'City Location',
    'Minimum Rating': 'Minimum Rating',
    'Accepted Insurance': 'Accepted Insurance',
    '✅ MOH Verified': '✅ MOH Verified',
    '🟢 Active Facility': '🟢 Active Facility',
    'View Facility →': 'View Facility →',
    'specialist doctor(s) at this facility': 'specialist doctor(s) at this facility',
    'Years Exp': 'Years Exp',
    '🟢 Available today': '🟢 Available today',
    '🟡 Tomorrow': '🟡 Tomorrow',
    'Next Slot:': 'Next Slot:',
    'Book appointment': 'Book appointment',
    'Show fewer doctors': 'Show fewer doctors',
    'Show more doctors at this facility': 'Show more doctors at this facility',
    'No medical clinics found matching your current filter criteria. Click "Clear all" to reset filters.': 'No medical clinics found matching your current filter criteria. Click "Clear all" to reset filters.',
    'Search Placeholder': 'Search by clinic name, doctor, city or specialty...',
    'Specialties:': 'Specialties:',
    'Accepted Insurance:': 'Accepted Insurance:',
    'Accepted Insurance Provider': 'Accepted Insurance Provider',
    'Self-Pay / Direct': 'Self-Pay / Direct',
    'Languages:': 'Languages:',
    'Available Today': 'Available Today',
    '🩺 Medical Specialty': '🩺 Medical Specialty',
    '⭐ Min Rating': '⭐ Min Rating',
    '🏥 Accepted Insurance': '🏥 Accepted Insurance',
    'doctor(s)': 'doctor(s)',
    // How it works
    'How it works': 'How it works',
    'Three steps to your appointment': 'Three steps to your appointment',
    'Search for a clinic': 'Search for a clinic',
    'Search by clinic name, city location, specialty or doctor. Filter by ratings, language, and insurance.': 'Search by clinic name, city location, specialty or doctor. Filter by ratings, language, and insurance.',
    'Choose your doctor': 'Choose your doctor',
    'Review doctor credentials, experience, spoken languages, and live open slots.': 'Review doctor credentials, experience, spoken languages, and live open slots.',
    'Book your appointment': 'Book your appointment',
    'Select your preferred date & time slot. Confirm directly into the clinic system.': 'Select your preferred date & time slot. Confirm directly into the clinic system.',
    // Features
    '✦ Platform Features': '✦ Platform Features',
    'More than booking. A complete care platform.': 'More than booking. A complete care platform.',
    'Connected care across clinics, doctors, and patient records.': 'Connected care across clinics, doctors, and patient records.',
    'Secure Consultation Chat': 'Secure Consultation Chat',
    'Direct doctor-patient messaging with attachment support for medical records and prescriptions.': 'Direct doctor-patient messaging with attachment support for medical records and prescriptions.',
    'Case Discussion Rooms': 'Case Discussion Rooms',
    'Multidisciplinary case rooms enabling doctors across clinics to collaborate on patient care.': 'Multidisciplinary case rooms enabling doctors across clinics to collaborate on patient care.',
    'Lab Results & Test Reports': 'Lab Results & Test Reports',
    'Direct upload, preview, and download of clinical lab reports with reference range tracking.': 'Direct upload, preview, and download of clinical lab reports with reference range tracking.',
    'Digital Prescriptions': 'Digital Prescriptions',
    'Digital Prescriptions Body': 'Instant e-prescriptions issued directly by verified medical professionals.',
    'Unified Health Record': 'Unified Health Record',
    'Unified Health Record Body': 'Centralized medical history, vital signs, allergies, and chronic condition tracking.',
    'Privacy & Security': 'Privacy & Security',
    'Privacy & Security Body': 'Strict data governance aligned with Saudi MOH and HIPAA healthcare standards.',
    // Testimonials
    '💬 Verified Experience': '💬 Verified Experience',
    'Trusted across': 'Trusted across',
    'Saudi Arabia': 'Saudi Arabia',
    'Saudi MOH': 'Saudi MOH',
    'Verified License': 'Verified License',
    'Naphies': 'Naphies',
    'Interoperable': 'Interoperable',
    'HIPAA': 'HIPAA',
    'Compliant': 'Compliant',
    'Bilingual': 'Bilingual',
    // CTA & Footer
    '🚀 For Clinics & Doctors': '🚀 For Clinics & Doctors',
    'List your clinic.': 'List your clinic.',
    'Reach more patients.': 'Reach more patients.',
    'CTA subtitle': 'Join Saudi Arabia\'s verified healthcare provider platform with your branches and doctors live in 48 hours.',
    'Sign up / List clinic free →': 'Sign up / List clinic free →',
    'Sign in to portal': 'Sign in to portal',
    'Footer description': 'Connecting patients to verified clinics and specialist doctors across Saudi Arabia.',
    'For Patients': 'For Patients',
    'My health record': 'My health record',
    'For Clinics': 'For Clinics',
    'Clinic dashboard': 'Clinic dashboard',
    'System': 'System',
    'Saudi MOH Aligned': 'Saudi MOH Aligned',
    'HIPAA Compliant': 'HIPAA Compliant',
    'All rights reserved.': 'All rights reserved.',
    'Footer Bottom': 'HIPAA compliant · Naphies ready · Arabic & English',
    // Modals
    'Select Appointment Date *': 'Select Appointment Date *',
    'Available Slots for': 'Available Slots for',
    'No open slots warning': 'No open time slots found for this date. Please select another date.',
    'Appointment Type': 'Appointment Type',
    'Session Mode': 'Session Mode',
    'Reason for Visit (Optional)': 'Reason for Visit (Optional)',
    'Selected:': 'Selected:',
    'Processing Booking...': 'Processing Booking...',
    'Confirm Appointment Booking →': 'Confirm Appointment Booking →',
    'About Facility': 'About Facility',
    'Contact Information': 'Contact Information',
    'Facility Status': 'Facility Status',
    'Branches & Locations': 'Branches & Locations',
    'Close Facility Details': 'Close Facility Details',
    // General
    'Registration ID:': 'Registration ID:',
    'Spoken Languages': 'Spoken Languages',
    'No languages documented.': 'No languages documented.',
    'Professional Biography': 'Professional Biography',
    'No bio notes provided.': 'No bio notes provided.',
    'Associated Clinics & Locations': 'Associated Clinics & Locations',
    'Primary Location': 'Primary Location',
    'Department:': 'Department:',
    'Fee:': 'Fee:',
    'Joined:': 'Joined:',
    'No registered clinical locations assigned.': 'No registered clinical locations assigned.',
    'Academic Qualifications': 'Academic Qualifications',
    'No qualifications recorded on profile file.': 'No qualifications recorded on profile file.',
    'Year': 'Year',
    'Professional Credentials, Bio & Qualifications': 'Professional Credentials, Bio & Qualifications',
    'Bio & General Details': 'Bio & General Details',
    'Specialties': 'Specialties',
    'Qualifications': 'Qualifications',
    'Clinics': 'Clinics',
    'Save General Profile': 'Save General Profile',
    'Experience': 'Experience',
    'Years': 'Years',
    'Rating:': 'Rating:',
    'reviews': 'reviews',
    'Standard Fee:': 'Standard Fee:',
    'SAR': 'SAR',
    'Language *': 'Language *',
    'Proficiency *': 'Proficiency *',
    '+ Add Language': '+ Add Language',
    'Remove': 'Remove',
    'Language': 'Language',
    'Proficiency Level': 'Proficiency Level',
    'Actions': 'Actions',
    'No languages listed on your profile yet.': 'No languages listed on your profile yet.',
    'Degree Title': 'Degree Title',
    'University / Institution': 'University / Institution',
    'Country & Year': 'Country & Year',
    'Degree *': 'Degree *',
    'Institution / University *': 'Institution / University *',
    'Country *': 'Country *',
    'Year Obtained *': 'Year Obtained *',
    '+ Add Degree': '+ Add Degree',
    'No qualifications listed on your profile yet.': 'No qualifications listed on your profile yet.',
    // System Admin Global Configurations
    'Registered Patients': 'Registered Patients',
    'Clinic Facilities': 'Clinic Facilities',
    'Verified Doctors': 'Verified Doctors',
    'Monthly Volume (SAR)': 'Monthly Volume (SAR)',
    'Platform Reference Registries': 'Platform Reference Registries',
    'Manage system configurations, regional coverage, specialties, and doctor roster registries': 'Manage system configurations, regional coverage, specialties, and doctor roster registries',
    '+ Add Entry': '+ Add Entry',
    '🇸🇦 Cities & Regions': '🇸🇦 Cities & Regions',
    '🩺 Medical Specialties': '🩺 Medical Specialties',
    '🗣️ Spoken Languages': '🗣️ Spoken Languages',
    '🛡️ Insurance Panels': '🛡️ Insurance Panels',
    '👨‍⚕️ Doctors Roster': '👨‍⚕️ Doctors Roster',
    'Saudi Arabia Coverage': 'Saudi Arabia Coverage',
    '📍 Manage Localities': '📍 Manage Localities',
    'Edit City': 'Edit City',
    'Delete City': 'Delete City',
    '← Back to Cities': '← Back to Cities',
    'Localities in': 'Localities in',
    'Postal Code:': 'Postal Code:',
    'Medical specialty registry': 'Medical specialty registry',
    '🎓 Manage SubSpecialties': '🎓 Manage SubSpecialties',
    '← Back to Specialties': '← Back to Specialties',
    'SubSpecialties in': 'SubSpecialties in',
    'Medical sub-specialty branch': 'Medical sub-specialty branch',
    'No cities found in system database.': 'No cities found in system database.',
    'No localities found for this city.': 'No localities found for this city.',
    'No specialties found.': 'No specialties found.',
    'No sub-specialties found.': 'No sub-specialties found.',
    'No languages configured.': 'No languages configured.',
    'No insurance panels registered.': 'No insurance panels registered.',
    'No doctors found in system database.': 'No doctors found in system database.',
    'Showing active items on record': 'Showing active items on record',
    'Edit Locality': 'Edit Locality',
    'Delete Locality': 'Delete Locality',
    'Edit Specialty': 'Edit Specialty',
    'Delete Specialty': 'Delete Specialty',
    'Edit SubSpecialty': 'Edit SubSpecialty',
    'Delete SubSpecialty': 'Delete SubSpecialty',
    'Edit Language': 'Edit Language',
    'Delete Language': 'Delete Language',
    'Edit Insurance': 'Edit Insurance',
    'Delete Insurance': 'Delete Insurance',
    'Edit Doctor': 'Edit Doctor',
    'Delete Doctor': 'Delete Doctor',
    'Add City': 'Add City',
    'Add Locality': 'Add Locality',
    'Add Specialty': 'Add Specialty',
    'Add SubSpecialty': 'Add SubSpecialty',
    'Add Language': 'Add Language',
    'Add Insurance Panel': 'Add Insurance Panel',
    'Edit Insurance Panel': 'Edit Insurance Panel',
    'City Name (EN) *': 'City Name (EN) *',
    'City Name (AR) *': 'City Name (AR) *',
    'Country Code *': 'Country Code *',
    'Sort Order *': 'Sort Order *',
    'Locality Name (EN) *': 'Locality Name (EN) *',
    'Locality Name (AR) *': 'Locality Name (AR) *',
    'Postal Code': 'Postal Code',
    'Code *': 'Code *',
    'Category *': 'Category *',
    'Specialty Name (EN) *': 'Specialty Name (EN) *',
    'Specialty Name (AR) *': 'Specialty Name (AR) *',
    'SubSpecialty Name (EN) *': 'SubSpecialty Name (EN) *',
    'SubSpecialty Name (AR) *': 'SubSpecialty Name (AR) *',
    'Language Name (EN) *': 'Language Name (EN) *',
    'Language Name (AR) *': 'Language Name (AR) *',
    'ISO Code *': 'ISO Code *',
    'Provider Name (EN) *': 'Provider Name (EN) *',
    'Provider Name (AR) *': 'Provider Name (AR) *',
    'Logo Upload': 'Logo Upload',
    'Active Doctor Status': 'Active Doctor Status',
    'Bio / Profile Summary': 'Bio / Profile Summary',
    'Professional Title *': 'Professional Title *',
    'Doctor Full Name *': 'Doctor Full Name *',
    'MOH Registration # *': 'MOH Registration # *',
    'Years of Experience *': 'Years of Experience *',
    'Consultation Fee (SAR) *': 'Consultation Fee (SAR) *',
    // Patient Dashboard Browse Doctors
    'Browse Doctors': 'Browse Doctors',
    'Find and book consultations with top medical experts': 'Find and book consultations with top medical experts',
    'Search Doctor Name': 'Search Doctor Name',
    'Location / City': 'Location / City',
    'All Cities': 'All Cities',
    'All Ratings': 'All Ratings',
    'Spoken Language': 'Spoken Language',
    'Min Experience': 'Min Experience',
    'Max Consultation Fee': 'Max Consultation Fee',
    'Reset Filters': 'Reset Filters',
    'General Practitioner': 'General Practitioner',
    'Experience:': 'Experience:',
    'View Profile': 'View Profile',
    'Book Consultation': 'Book Consultation',
    'No Doctors Found': 'No Doctors Found',
    'Try adjusting your search query or reset filters to view all specialists.': 'Try adjusting your search query or reset filters to view all specialists.',
    'Show All Doctors': 'Show All Doctors',
    'Doctor Details': 'Doctor Details',
    'MOH License': 'MOH License',
    'Assigned Clinics & Locations': 'Assigned Clinics & Locations',
    'Primary Clinic': 'Primary Clinic',
    'Secondary': 'Secondary',
    'No qualifications recorded.': 'No qualifications recorded.',
    // Clinic Explorer
    'Search clinics...': 'Search clinics...',
    'No medical clinics found matching your current filter criteria.': 'No medical clinics found matching your current filter criteria.',
    'Select a Medical Clinic': 'Select a Medical Clinic',
    'Choose a clinic from the list on the left to view its active branches, operating schedules, and registered doctors roster.': 'Choose a clinic from the list on the left to view its active branches, operating schedules, and registered doctors roster.',
    'Back to Clinics List': 'Back to Clinics List',
    'Premier medical facility providing state of the art therapeutic and diagnostic healthcare solutions across the region.': 'Premier medical facility providing state of the art therapeutic and diagnostic healthcare solutions across the region.',
    'Select a Branch Location': 'Select a Branch Location',
    'No active clinic branch locations assigned.': 'No active clinic branch locations assigned.',
    'Primary': 'Primary',
    'Availability & Hours': 'Availability & Hours',
    'No schedules listed for this branch.': 'No schedules listed for this branch.',
    'No active specialist doctors assigned to this branch location.': 'No active specialist doctors assigned to this branch location.',
    'Select a Branch Location above': 'Select a Branch Location above',
    'Choose one of the active branch locations above to view its daily operating hours and list of available specialist doctors.': 'Choose one of the active branch locations above to view its daily operating hours and list of available specialist doctors.',
    'Closed': 'Closed',
    'from': 'from',
    'Consultation Fee:': 'Consultation Fee:',
    'Or choose another date:': 'Or choose another date:',
    'No open slots available for this doctor on the selected date.': 'No open slots available for this doctor on the selected date.',
    'Booked': 'Booked',
    'Blocked': 'Blocked',
    'Briefly describe your symptoms, medical concerns, or target goals for this visit...': 'Briefly describe your symptoms, medical concerns, or target goals for this visit...',
    // Auth additional
    'Welcome Back': 'Welcome Back',
    'Please enter your credentials to access your account': 'Please enter your credentials to access your account',
    'Please enter a valid email address.': 'Please enter a valid email address.',
    'Password must be at least 6 characters.': 'Password must be at least 6 characters.',
    'Sign In': 'Sign In',
    'or': 'or',
    'Continue with Google': 'Continue with Google',
    "Don't have an account?": "Don't have an account?",
    'Create an account': 'Create an account',
    'Create an Account': 'Create an Account',
    'Join MedConsult to manage consultations and records seamlessly': 'Join MedConsult to manage consultations and records seamlessly',
    'Full Name': 'Full Name',
    'Full name is required (min 2 characters).': 'Full name is required (min 2 characters).',
    'Phone Number': 'Phone Number',
    'Please enter a valid phone number.': 'Please enter a valid phone number.',
    'Preferred Language': 'Preferred Language',
    'Already have an account?': 'Already have an account?',
    'Symptoms placeholder': 'Symptoms or general consultation reason...',
    'MOH License:': 'MOH License:',
    'Premier medical facility description': 'Premier medical facility providing comprehensive specialist care.',
    'Active': 'Active',
    'Select Type': 'Select Type',
    'Select Mode': 'Select Mode',
    // Patient Home
    'Hello,': 'Hello,',
    'Welcome!': 'Welcome!',
    'Here is your general health summary and upcoming care schedule.': 'Here is your general health summary and upcoming care schedule.',
    'National ID:': 'National ID:',
    'Blood Type:': 'Blood Type:',
    'Unknown': 'Unknown',
    'Welcome to MedConsult! Please complete your patient profile to unlock bookings and health records.': 'Welcome to MedConsult! Please complete your patient profile to unlock bookings and health records.',
    'Initialize Profile Now': 'Initialize Profile Now',
    'Find doctors, clinics & slots': 'Find doctors, clinics & slots',
    'Prescriptions, vitals & labs': 'Prescriptions, vitals & labs',
    'Tele-consultations & advice': 'Tele-consultations & advice',
    'Upcoming Consultations': 'Upcoming Consultations',
    'Book New Appointment': 'Book New Appointment',
    '+ Book New Appointment': '+ Book New Appointment',
    'Cancel': 'Cancel',
    'No upcoming appointments booked.': 'No upcoming appointments booked.',
    'Need to see a doctor? Book a new consultation slot in seconds.': 'Need to see a doctor? Book a new consultation slot in seconds.',
    'Cancel Appointment': 'Cancel Appointment',
    'Are you sure you want to cancel your consultation with': 'Are you sure you want to cancel your consultation with',
    'on': 'on',
    'Reason for Cancellation': 'Reason for Cancellation',
    'Cancel placeholder': 'Please explain why you are cancelling...',
    'Cancel error': 'Cancellation reason is required (max 255 chars).',
    'Go Back': 'Go Back',
    'Confirm Cancellation': 'Confirm Cancellation',
    'Message Doctor': 'Message Doctor',
    'View EMR Records': 'View EMR Records',
    // Appointments Center
    'Appointment Center': 'Appointment Center',
    'Manage your upcoming consultations, view clinical session history, and modify scheduled visits.': 'Manage your upcoming consultations, view clinical session history, and modify scheduled visits.',
    'Consultation Mode': 'Consultation Mode',
    'From Date': 'From Date',
    'To Date': 'To Date',
    'Search Doctor': 'Search Doctor',
    'Search by doctor/department...': 'Search by doctor/department...',
    'Clear Filters': 'Clear Filters',
    'Scheduled Slot': 'Scheduled Slot',
    'Clinic & Department': 'Clinic & Department',
    'min': 'min',
    '🏢 In-Clinic': '🏢 In-Clinic',
    '💻 Video Call': '💻 Video Call',
    'View Details': 'View Details',
    'No appointments history matches the current filters.': 'No appointments history matches the current filters.',
    'Showing page': 'Showing page',
    'of': 'of',
    'total records': 'total records',
    'Appointment Specification Details': 'Appointment Specification Details',
    'Scheduled Date & Time': 'Scheduled Date & Time',
    'minutes duration': 'minutes duration',
    'Clinical Assignment': 'Clinical Assignment',
    'Consultation Details': 'Consultation Details',
    '🏢 In-Clinic Visit': '🏢 In-Clinic Visit',
    '💻 Video Call Session': '💻 Video Call Session',
    'Reason for Consultation': 'Reason for Consultation',
    'No specific reasons provided by the patient.': 'No specific reasons provided by the patient.',
    'Cancellation Information': 'Cancellation Information',
    'Status:': 'Status:',
    'Reason': 'Reason',
    'No reason provided': 'No reason provided',
    'Quick Shortcuts': 'Quick Shortcuts',
    'Write Review': 'Write Review',
    'Reschedule Visit': 'Reschedule Visit',
    'Go to Chat Session': 'Go to Chat Session',
    'Close Details': 'Close Details',
    'This action cannot be undone once confirmed.': 'This action cannot be undone once confirmed.',
    'Reason for Cancellation *': 'Reason for Cancellation *',
    'Please tell us why you need to cancel this appointment': 'Please tell us why you need to cancel this appointment',
    'Reason is required (max 255 chars).': 'Reason is required (max 255 chars).',
    'Reschedule Consultation': 'Reschedule Consultation',
    'Select New Appointment Date *': 'Select New Appointment Date *',
    'Confirm Reschedule': 'Confirm Reschedule',
    'Processing...': 'Processing...',
    'Rate Your Consultation': 'Rate Your Consultation',
    'Doctor Review': 'Doctor Review',
    'Overall Doctor Rating (1-5) *': 'Overall Doctor Rating (1-5) *',
    'Bedside *': 'Bedside *',
    'Knowledge *': 'Knowledge *',
    'Wait Time *': 'Wait Time *',
    'Clinic Review': 'Clinic Review',
    'Overall Clinic Rating (1-5) *': 'Overall Clinic Rating (1-5) *',
    'Cleanliness *': 'Cleanliness *',
    'Staff *': 'Staff *',
    'Written Feedback (Optional)': 'Written Feedback (Optional)',
    'Share details of your experience...': 'Share details of your experience...',
    'Max 2000 characters': 'Max 2000 characters',
    'Submit this review anonymously': 'Submit this review anonymously',
    'Submit Feedback': 'Submit Feedback',
    // Tele-Consultations
    'Book New Consultation': 'Book New Consultation',
    'No consultation records found.': 'No consultation records found.',
    'Opened:': 'Opened:',
    'Consulting with': 'Consulting with',
    'Urgent': 'Urgent',
    'No messages yet. Send a message below to start the conversation.': 'No messages yet. Send a message below to start the conversation.',
    'Type your message here...': 'Type your message here...',
    'Send': 'Send',
    'This consultation has been closed.': 'This consultation has been closed.',
    'Rate Consultation': 'Rate Consultation',
    'Select a consultation from the left list to view messages.': 'Select a consultation from the left list to view messages.',
    'Book a Tele-Consultation': 'Book a Tele-Consultation',
    'Select Doctor': 'Select Doctor',
    '-- Choose a Doctor --': '-- Choose a Doctor --',
    'Doctor selection is required.': 'Doctor selection is required.',
    'Subject / Reason for Consultation': 'Subject / Reason for Consultation',
    'Briefly describe your health concern': 'Briefly describe your health concern',
    'Subject is required.': 'Subject is required.',
    'Mark as Urgent': 'Mark as Urgent',
    'OPEN': 'Open',
    'IN_PROGRESS': 'In Progress',
    'CLOSED': 'Closed',
    // Health Metrics
    'Health Metrics & Medical History': 'Health Metrics & Medical History',
    'Please initialize your General Patient Profile before entering your medical metrics.': 'Please initialize your General Patient Profile before entering your medical metrics.',
    'Edit Metrics': 'Edit Metrics',
    'Height (cm)': 'Height (cm)',
    'Calculated BMI': 'Calculated BMI',
    'Smoking Status': 'Smoking Status',
    'Alcohol Intake': 'Alcohol Intake',
    'Surgical History': 'Surgical History',
    'List any past surgeries...': 'List any past surgeries...',
    'Family Medical History': 'Family Medical History',
    'List hereditary conditions in your family...': 'List hereditary conditions in your family...',
    'Additional Notes': 'Additional Notes',
    'Other medical notes...': 'Other medical notes...',
    'Save Changes': 'Save Changes',
    'Known Allergies': 'Known Allergies',
    'Add Allergy': 'Add Allergy',
    'Reaction:': 'Reaction:',
    'No allergies listed on record.': 'No allergies listed on record.',
    'Chronic Conditions': 'Chronic Conditions',
    'Add Condition': 'Add Condition',
    'ICD-10 Code:': 'ICD-10 Code:',
    'Diagnosed:': 'Diagnosed:',
    'No chronic conditions listed.': 'No chronic conditions listed.',
    'Add Known Allergy': 'Add Known Allergy',
    'Allergen Name': 'Allergen Name',
    'E.g. Penicillin, Peanuts': 'E.g. Penicillin, Peanuts',
    'Allergy Type': 'Allergy Type',
    'Severity': 'Severity',
    'Allergic Reaction Details': 'Allergic Reaction Details',
    'E.g. Skin rashes, Anaphylaxis': 'E.g. Skin rashes, Anaphylaxis',
    'Register Chronic Condition': 'Register Chronic Condition',
    'Condition Name': 'Condition Name',
    'E.g. Diabetes Mellitus Type II': 'E.g. Diabetes Mellitus Type II',
    'ICD-10 Code': 'ICD-10 Code',
    'E.g. E11.9': 'E.g. E11.9',
    'Must be a valid ICD-10 format.': 'Must be a valid ICD-10 format.',
    'Diagnosis Date': 'Diagnosis Date',
    'Condition Status': 'Condition Status',
    'Notes': 'Notes',
    'Relevant comments...': 'Relevant comments...',
    // EMR additional
    'Registration Required': 'Registration Required',
    'Please initialize your General Patient Profile before accessing your Electronic Medical Records (EMR).': 'Please initialize your General Patient Profile before accessing your Electronic Medical Records (EMR).',
    'Setup Profile': 'Setup Profile',
    'Prescriptions & Adherence': 'Prescriptions & Adherence',
    'Vitals History Log': 'Vitals History Log',
    'Lab Test Reports': 'Lab Test Reports',
    'Prescription Reference:': 'Prescription Reference:',
    'Local Record': 'Local Record',
    'Issued:': 'Issued:',
    'Valid Until:': 'Valid Until:',
    'ACTIVE': 'ACTIVE',
    'EXPIRED': 'EXPIRED',
    'Diagnosis & Clinical Notes': 'Diagnosis & Clinical Notes',
    'No diagnosis notes available.': 'No diagnosis notes available.',
    'Prescribed Medications': 'Prescribed Medications',
    'Dosage:': 'Dosage:',
    'Route:': 'Route:',
    'Frequency:': 'Frequency:',
    'Duration:': 'Duration:',
    'Days': 'Days',
    'Refills:': 'Refills:',
    'Used': 'Used',
    'Took Today': 'Took Today',
    'Latest:': 'Latest:',
    'Taken': 'Taken',
    'Skipped': 'Skipped',
    'None recorded': 'None recorded',
    'No prescriptions found on your EMR file.': 'No prescriptions found on your EMR file.',
    'Vital Metrics History': 'Vital Metrics History',
    'Log New Vitals': 'Log New Vitals',
    'Blood Pressure:': 'Blood Pressure:',
    'Heart Rate:': 'Heart Rate:',
    'Blood Glucose:': 'Blood Glucose:',
    'Weight:': 'Weight:',
    'O2 Saturation:': 'O2 Saturation:',
    'No vitals records warning': 'No vitals records listed. Click above to log your first metric.',
    'Report:': 'Report:',
    'Date:': 'Date:',
    'NORMAL': 'NORMAL',
    'ABNORMAL': 'ABNORMAL',
    'CRITICAL': 'CRITICAL',
    'Doctors Annotations': 'Doctor\'s Annotations',
    'No clinical annotation added.': 'No clinical annotation added.',
    'Attachment Document': 'Attachment Document',
    'Download Attachment': 'Download Attachment',
    'No lab report files warning': 'No lab report files uploaded on your file.',
    'Log New Vital Entry': 'Log New Vital Entry',
    'Systolic BP (mmHg)': 'Systolic BP (mmHg)',
    'Diastolic BP (mmHg)': 'Diastolic BP (mmHg)',
    'Heart Rate (BPM)': 'Heart Rate (BPM)',
    'Blood Glucose (mmol/L)': 'Blood Glucose (mmol/L)',
    'Weight (kg)': 'Weight (kg)',
    'Body Temp (°C)': 'Body Temp (°C)',
    'Log Notes': 'Log Notes',
    'Context, symptom notes placeholder': 'Context, symptom notes...',
    'Record Vitals': 'Record Vitals',
    'PATIENT_APP': 'Patient App',
    'DOCTOR_ENTRY': 'Doctor Entry',
    'ORAL': 'Oral',
    'INTRAVENOUS': 'Intravenous',
    'Twice': 'Twice',
    'Once': 'Once',
    'Three times': 'Three times',
    'Four times': 'Four times',
    // Booking Wizard
    'Please initialize your General Patient Profile before booking a new appointment.': 'Please initialize your General Patient Profile before booking a new appointment.',
    'Schedule Your Consultation': 'Schedule Your Consultation',
    'Select your preferred doctor, clinic branch, and appointment slot': 'Select your preferred doctor, clinic branch, and appointment slot',
    'Follow the steps below to choose your doctor, date, and time slot': 'Follow the steps below to choose your doctor, date, and time slot',
    'SA MOH Verified Network': 'SA MOH Verified Network',
    'Doctor': 'Doctor',
    'Clinic': 'Clinic',
    'Date': 'Date',
    'Date & Time': 'Date & Time',
    'Slot': 'Slot',
    'Confirm': 'Confirm',
    'Step 1: Choose Specialist Doctor': 'Step 1: Choose Specialist Doctor',
    'Step 1: Choose Specialist Doctor *': 'Step 1: Choose Specialist Doctor *',
    'Browse our verified doctors panel and select a specialist to check clinic locations': 'Browse our verified doctors panel and select a specialist to check clinic locations',
    'Search doctor name...': 'Search doctor name...',
    'Active booking exists with this doctor': 'Active booking exists with this doctor',
    'Yrs Exp': 'Yrs Exp',
    '-- Select Specialist Doctor --': '-- Select Specialist Doctor --',
    'View Doctor Profile, Biography & Specialties': 'View Doctor Profile, Biography & Specialties',
    'Step 2: Choose Clinic Location': 'Step 2: Choose Clinic Location',
    'Step 2: Select Clinic Location *': 'Step 2: Select Clinic Location *',
    'Select from the branch locations where this doctor is currently practicing': 'Select from the branch locations where this doctor is currently practicing',
    '-- Choose Clinic Location --': '-- Choose Clinic Location --',
    'No Branches Registered': 'No Branches Registered',
    'This doctor is not assigned to any active clinic branch locations.': 'This doctor is not assigned to any active clinic branch locations.',
    'No active clinic branch locations assigned to this doctor.': 'No active clinic branch locations assigned to this doctor.',
    'Back to Doctors': 'Back to Doctors',
    'Back': 'Back',
    'Next': 'Next',
    'Step 3: Appointment Date & Time': 'Step 3: Appointment Date & Time',
    'Step 3: Choose Appointment Date *': 'Step 3: Choose Appointment Date *',
    'Select a booking date to see available consultation time slots': 'Select a booking date to see available consultation time slots',
    'Select Date': 'Select Date',
    'Or choose any date:': 'Or choose any date:',
    'Available Slots': 'Available Slots',
    'Step 4: Select Available Time Slot *': 'Step 4: Select Available Time Slot *',
    'No Time Slots Available': 'No Time Slots Available',
    'There are no open slots on the selected date. Try choosing another day.': 'There are no open slots on the selected date. Try choosing another day.',
    'Step 4: Confirm & Book': 'Step 4: Confirm & Book',
    'Step 5: Confirm & Finalize Details': 'Step 5: Confirm & Finalize Details',
    'Provide appointment reason and choose session mode to book consultation': 'Provide appointment reason and choose session mode to book consultation',
    'Consultation Details Summary': 'Consultation Details Summary',
    'Clinic Branch': 'Clinic Branch',
    'Consultation Fee': 'Consultation Fee',
    'Session Mode *': 'Session Mode *',
    'In Clinic': 'In Clinic',
    'Visit the doctor physically at the selected branch location.': 'Visit the doctor physically at the selected branch location.',
    'Virtual': 'Virtual',
    'Consult online via text chat and attachments upload.': 'Consult online via text chat and attachments upload.',
    'Appointment Type *': 'Appointment Type *',
    'New Patient': 'New Patient',
    'First consultation for this specific illness or checkup.': 'First consultation for this specific illness or checkup.',
    'Follow Up': 'Follow Up',
    'Routine diagnostic checkup or continuous test reviews.': 'Routine diagnostic checkup or continuous test reviews.',
    'Reason for Visit / Symptoms': 'Reason for Visit / Symptoms',
    'Reason for Visit / Symptoms (Optional)': 'Reason for Visit / Symptoms (Optional)',
    'Type short reasons or symptoms...': 'Type short reasons or symptoms...',
    'Confirm & Book Appointment': 'Confirm & Book Appointment',
    'NEW PATIENT': 'New Patient',
    'FOLLOW UP': 'Follow Up',
    'CONSULTATION': 'Consultation',
    'EMERGENCY': 'Emergency',
    'IN CLINIC': 'In Clinic',
    'VIDEO CONSULTATION': 'Video Consultation',
    'CHATTING': 'Chatting'
  },
  ar: {
    // Database Specialties fixes
    'SFB': 'طب الأسرة',
    'SPOFE': 'الطب الرياضي',

    // Menu
    'Home Dashboard': 'لوحة التحكم الرئيسية',
    'Clinics & Branches': 'العيادات والفروع',
    'My Appointments': 'مواعيدي',
    'Medical Records (EMR)': 'السجلات الطبية (EMR)',
    'Book Appointment': 'حجز موعد',
    'Tele-Consultations': 'الاستشارات الطبية',
    'My General Profile': 'الملف الشخصي العام',
    'Personal Health Metrics': 'المؤشرات الصحية الشخصية',
    'Professional Profile': 'الملف المهني',
    'Consultation Schedule': 'جدول الاستشارات',
    'My Consultations': 'استشاراتي',
    'Case Rooms': 'غرف الحالات',
    'Patient EMR Records': 'سجلات المرضى (EMR)',
    'Availability & Slots': 'المواعيد الشاغرة',
    'Dashboard': 'لوحة التحكم',
    'My Clinics': 'عياداتي',
    'Doctors Roster': 'قائمة الأطباء',
    'Global Configurations': 'الإعدادات العامة',
    'Public Portal Home': 'البوابة العامة',
    'Logout': 'تسجيل الخروج',
    'View Public Portal': 'عرض البوابة العامة',
    'Dashboard Title': 'لوحة التحكم',
    // Landing
    'Find a clinic': 'البحث عن عيادة',
    'Platform features': 'مزايا المنصة',
    'Verified Network': 'الشبكة المعتمدة',
    'Go to Portal Dashboard →': 'الانتقال للوحة التحكم ←',
    'Sign in': 'تسجيل الدخول',
    'Sign up / List Clinic': 'تسجيل جديد / إضافة عيادة',
    'MOH Eyebrow': '🇸🇦 بوابة الرعاية الصحية المعتمدة في المملكة والخليج',
    'Find a clinic.Connect with the right doctor.': 'ابحث عن عيادة. تواصل مع الطبيب المناسب.',
    'Search verified private clinics across Saudi Arabia. Browse doctors, filter by specialty, city, language, and availability — and book real appointments online.': 'ابحث في العيادات الخاصة المعتمدة في المملكة العربية السعودية. تصفح الأطباء، ورشح حسب التخصص، المدينة، اللغة، والتوفر - واحجز مواعيدك الطبية مباشرة عبر الإنترنت.',
    'Search clinics': 'البحث عن عيادات',
    'All Cities / Areas': '📍 جميع المدن / المناطق',
    'Specialty:': 'التخصص:',
    'All': 'الكل',
    'All clinics verified by MOH': 'جميع العيادات معتمدة من وزارة الصحة',
    'Real-time doctor schedules': 'مواعيد حقيقية ومباشرة للأطباء',
    'HIPAA-compliant system': 'نظام متوافق مع معايير HIPAA',
    'Arabic & English': 'باللغتين العربية والإنجليزية',
    'Verified Medical Clinics': 'العيادات الطبية المعتمدة',
    'Showing clinics': 'عرض العيادات من قاعدة البيانات',
    'Sort by:': 'ترتيب حسب:',
    'Clinics List': 'قائمة العيادات',
    'Filter Specialties': 'تصفية التخصصات',
    // Filters & Results
    'Filters & Refinements': 'التصفية والخيارات',
    'Clear all': 'مسح الكل',
    'Doctor Availability': 'توفر الطبيب',
    'Available Today Only': 'متاح اليوم فقط',
    'Medical Specialty': 'التخصص الطبي',
    'City Location': 'المدينة / المنطقة',
    'Minimum Rating': 'الحد الأدنى للتقييم',
    'Accepted Insurance': 'التأمين المقبول',
    '✅ MOH Verified': '✅ معتمد من وزارة الصحة',
    '🟢 Active Facility': '🟢 منشأة نشطة',
    'View Facility →': 'عرض التفاصيل ←',
    'specialist doctor(s) at this facility': 'أطباء أخصائيين في هذه المنشأة',
    'Years Exp': 'سنة خبرة',
    '🟢 Available today': '🟢 متاح اليوم',
    '🟡 Tomorrow': '🟡 متاح غداً',
    'Next Slot:': 'الموعد القادم:',
    'Book appointment': 'حجز موعد',
    'Show fewer doctors': 'عرض أطباء أقل',
    'Show more doctors at this facility': 'عرض المزيد من الأطباء في هذه المنشأة',
    'No medical clinics found matching your current filter criteria. Click "Clear all" to reset filters.': 'لم يتم العثور على أي عيادات مطابقة لمعايير البحث الحالية. اضغط على "مسح الكل" لإعادة ضبط التصفية.',
    'Search Placeholder': 'البحث باسم العيادة، الطبيب، المدينة أو التخصص...',
    'Specialties:': 'التخصصات:',
    'Accepted Insurance:': 'التأمين المقبول:',
    'Accepted Insurance Provider': 'مزود تأمين مقبول',
    'Self-Pay / Direct': 'دفع مباشر / بدون تأمين',
    'Languages:': 'اللغات المتاحة:',
    'Available Today': 'متاح اليوم',
    '🩺 Medical Specialty': '🩺 التخصص الطبي',
    '⭐ Min Rating': '⭐ الحد الأدنى للتقييم',
    '🏥 Accepted Insurance': '🏥 التأمين المقبول',
    'doctor(s)': 'أطباء',
    // How it works
    'How it works': 'طريقة العمل',
    'Three steps to your appointment': 'ثلاث خطوات لحجز موعدك',
    'Search for a clinic': 'البحث عن عيادة',
    'Search by clinic name, city location, specialty or doctor. Filter by ratings, language, and insurance.': 'البحث عن طريق اسم العيادة، المدينة، التخصص أو الطبيب. والتصفية حسب التقييمات، اللغات، والتأمين.',
    'Choose your doctor': 'اختيار طبيبك',
    'Review doctor credentials, experience, spoken languages, and live open slots.': 'مراجعة مؤهلات الطبيب، سنوات الخبرة، اللغات التي يتحدث بها، والمواعيد المتاحة مباشرة.',
    'Book your appointment': 'حجز الموعد',
    'Select your preferred date & time slot. Confirm directly into the clinic system.': 'حدد التاريخ ووقت الموعد المفضلين لديك. وأكد الحجز مباشرة في نظام العيادة.',
    // Features
    '✦ Platform Features': '✦ مزايا المنصة',
    'More than booking. A complete care platform.': 'أكثر من مجرد حجز. منصة رعاية صحية متكاملة.',
    'Connected care across clinics, doctors, and patient records.': 'رعاية متصلة تربط العيادات والأطباء والسجلات الطبية للمرضى.',
    'Secure Consultation Chat': 'دردشة استشارات آمنة',
    'Direct doctor-patient messaging with attachment support for medical records and prescriptions.': 'مراسلة مباشرة بين الطبيب والمريض مع إمكانية إرفاق الملفات الطبية والوصفات.',
    'Case Discussion Rooms': 'غرف مناقشة الحالات',
    'Multidisciplinary case rooms enabling doctors across clinics to collaborate on patient care.': 'غرف استشارية مشتركة تمكن الأطباء من مختلف العيادات من التعاون في رعاية المرضى.',
    'Lab Results & Test Reports': 'نتائج المختبر والتقارير الطبية',
    'Direct upload, preview, and download of clinical lab reports with reference range tracking.': 'رفع ومعاينة وتنزيل تقارير المختبر الطبية مباشرة مع تتبع النسب المرجعية.',
    'Digital Prescriptions': 'الوصفات الطبية الرقمية',
    'Digital Prescriptions Body': 'وصفات طبية إلكترونية فورية تصدر مباشرة من كوادر طبية معتمدة.',
    'Unified Health Record': 'سجل صحي موحد',
    'Unified Health Record Body': 'ملف طبي مركزي يحتوي على التاريخ المرضي، المؤشرات الحيوية، الحساسية، والأمراض المزمنة.',
    'Privacy & Security': 'الخصوصية والأمان',
    'Privacy & Security Body': 'حوكمة صارمة للبيانات تتماشى مع معايير وزارة الصحة السعودية ومعايير HIPAA الصحية.',
    // Testimonials
    '💬 Verified Experience': '💬 تجربة معتمدة',
    'Trusted across': 'موثوق في جميع أنحاء',
    'Saudi Arabia': 'المملكة العربية السعودية',
    'Saudi MOH': 'وزارة الصحة السعودية',
    'Verified License': 'ترخيص معتمد',
    'Naphies': 'نفيس',
    'Interoperable': 'ربط متكامل',
    'HIPAA': 'HIPAA',
    'Compliant': 'متوافق بالكامل',
    'Bilingual': 'ثنائي اللغة',
    // CTA & Footer
    '🚀 For Clinics & Doctors': '🚀 للعيادات والأطباء',
    'List your clinic.': 'سجل عيادتك.',
    'Reach more patients.': 'تواصل مع مرضى أكثر.',
    'CTA subtitle': 'انضم إلى منصة مزودي الرعاية الصحية المعتمدة في السعودية مع تفعيل فروعك وأطبائك خلال ٤٨ ساعة.',
    'Sign up / List clinic free →': 'تسجيل جديد / أضف عيادتك مجاناً ←',
    'Sign in to portal': 'تسجيل دخول البوابة',
    'Footer description': 'ربط المرضى بالعيادات المعتمدة والأطباء الأخصائيين في المملكة العربية السعودية.',
    'For Patients': 'للمرضى',
    'My health record': 'سجلي الصحي',
    'For Clinics': 'للعيادات',
    'Clinic dashboard': 'لوحة تحكم العيادة',
    'System': 'النظام',
    'Saudi MOH Aligned': 'متوافق مع وزارة الصحة',
    'HIPAA Compliant': 'متوافق مع معايير HIPAA',
    'All rights reserved.': 'جميع الحقوق محفوظة.',
    'Footer Bottom': 'متوافق مع HIPAA · جاهز للربط مع نفيس · باللغتين العربية والإنجليزية',
    // Modals
    'Select Appointment Date *': 'اختر تاريخ الموعد *',
    'Available Slots for': 'المواعيد المتاحة لتاريخ',
    'No open slots warning': 'لا توجد مواعيد متاحة في هذا اليوم. يرجى اختيار تاريخ آخر.',
    'Appointment Type': 'نوع الموعد',
    'Session Mode': 'نوع الجلسة',
    'Reason for Visit (Optional)': 'سبب الزيارة (اختياري)',
    'Selected:': 'المحدد:',
    'Processing Booking...': 'جاري إتمام الحجز...',
    'Confirm Appointment Booking →': 'تأكيد حجز الموعد ←',
    'About Facility': 'حول المنشأة',
    'Contact Information': 'معلومات الاتصال',
    'Facility Status': 'حالة المنشأة',
    'Branches & Locations': 'الفروع والمواقع',
    'Close Facility Details': 'إغلاق تفاصيل المنشأة',
    // General
    'Registration ID:': 'رقم التسجيل:',
    'Spoken Languages': 'اللغات المتحدثة',
    'No languages documented.': 'لا توجد لغات مسجلة.',
    'Professional Biography': 'السيرة المهنية',
    'No bio notes provided.': 'لا توجد نبذة تعريفية.',
    'Associated Clinics & Locations': 'العيادات والمواقع التابعة',
    'Primary Location': 'الموقع الرئيسي',
    'Department:': 'القسم:',
    'Fee:': 'رسوم الكشف:',
    'Joined:': 'تاريخ الانضمام:',
    'No registered clinical locations assigned.': 'لا توجد مواقع عيادات مسجلة بعد.',
    'Academic Qualifications': 'المؤهلات العلمية الأكاديمية',
    'No qualifications recorded on profile file.': 'لا توجد مؤهلات مسجلة في الملف الشخصي.',
    'Year': 'سنة',
    'Professional Credentials, Bio & Qualifications': 'الاعتمادات المهنية، السيرة الذاتية والمؤهلات',
    'Bio & General Details': 'السيرة الذاتية والتفاصيل العامة',
    'Specialties': 'التخصصات',
    'Qualifications': 'المؤهلات',
    'Clinics': 'العيادات التابعة',
    'Save General Profile': 'حفظ الملف التعريفي العام',
    'Experience': 'الخبرة',
    'Years': 'سنوات',
    'Rating:': 'التقييم:',
    'reviews': 'تقييمات',
    'Standard Fee:': 'الرسوم القياسية:',
    'SAR': 'ريال سعودي',
    'Language *': 'اللغة *',
    'Proficiency *': 'مستوى الإتقان *',
    '+ Add Language': '+ إضافة لغة',
    'Remove': 'حذف',
    'Language': 'اللغة',
    'Proficiency Level': 'مستوى الإتقان',
    'Actions': 'العمليات',
    'No languages listed on your profile yet.': 'لم يتم إضافة أي لغات لملفك الشخصي بعد.',
    'Degree Title': 'عنوان الدرجة',
    'University / Institution': 'الجامعة / المؤسسة',
    'Country & Year': 'البلد والسنة',
    'Degree *': 'الدرجة العلمية *',
    'Institution / University *': 'المؤسسة / الجامعة *',
    'Country *': 'البلد *',
    'Year Obtained *': 'سنة الحصول عليها *',
    '+ Add Degree': '+ إضافة درجة',
    'No qualifications listed on your profile yet.': 'لا توجد مؤهلات مسجلة في ملفك الشخصي بعد.',
    // System Admin Global Configurations
    'Registered Patients': 'المرضى المسجلين',
    'Clinic Facilities': 'المنشآت والعيادات',
    'Verified Doctors': 'الأطباء المعتمدين',
    'Monthly Volume (SAR)': 'الحجم الشهري (ريال)',
    'Platform Reference Registries': 'سجلات المنصة المرجعية',
    'Manage system configurations, regional coverage, specialties, and doctor roster registries': 'إدارة إعدادات النظام، التغطية الجغرافية، التخصصات، وقوائم الأطباء',
    '+ Add Entry': '+ إضافة عنصر',
    '🇸🇦 Cities & Regions': '🇸🇦 المدن والمناطق',
    '🩺 Medical Specialties': '🩺 التخصصات الطبية',
    '🗣️ Spoken Languages': '🗣️ اللغات المتاحة',
    '🛡️ Insurance Panels': '🛡️ شركات التأمين',
    '👨‍⚕️ Doctors Roster': '👨‍⚕️ قائمة الأطباء',
    'Saudi Arabia Coverage': 'تغطية المملكة العربية السعودية',
    '📍 Manage Localities': '📍 إدارة الأحياء/المناطق',
    'Edit City': 'تعديل المدينة',
    'Delete City': 'حذف المدينة',
    '← Back to Cities': '← العودة إلى المدن',
    'Localities in': 'الأحياء في',
    'Postal Code:': 'الرمز البريدي:',
    'Medical specialty registry': 'سجل التخصصات الطبية',
    '🎓 Manage SubSpecialties': '🎓 إدارة التخصصات الفرعية',
    '← Back to Specialties': '← العودة إلى التخصصات',
    'SubSpecialties in': 'التخصصات الفرعية في',
    'Medical sub-specialty branch': 'فرع التخصص الطبي',
    'No cities found in system database.': 'لم يتم العثور على مدن في قاعدة البيانات.',
    'No localities found for this city.': 'لم يتم العثور على أحياء لهذه المدينة.',
    'No specialties found.': 'لم يتم العثور على تخصصات.',
    'No sub-specialties found.': 'لم يتم العثور على تخصصات فرعية.',
    'No languages configured.': 'لم يتم إعداد لغات.',
    'No insurance panels registered.': 'لم يتم تسجيل شركات تأمين.',
    'No doctors found in system database.': 'لم يتم العثور على أطباء في قاعدة البيانات.',
    'Showing active items on record': 'عرض العناصر النشطة في السجل',
    'Edit Locality': 'تعديل الحي',
    'Delete Locality': 'حذف الحي',
    'Edit Specialty': 'تعديل التخصص',
    'Delete Specialty': 'حذف التخصص',
    'Edit SubSpecialty': 'تعديل التخصص الفرعي',
    'Delete SubSpecialty': 'حذف التخصص الفرعي',
    'Edit Language': 'تعديل اللغة',
    'Delete Language': 'حذف اللغة',
    'Edit Insurance': 'تعديل التأمين',
    'Delete Insurance': 'حذف التأمين',
    'Edit Doctor': 'تعديل الطبيب',
    'Delete Doctor': 'حذف الطبيب',
    'Add City': 'إضافة مدينة',
    'Add Locality': 'إضافة حي',
    'Add Specialty': 'إضافة تخصص',
    'Add SubSpecialty': 'إضافة تخصص فرعي',
    'Add Language': 'إضافة لغة',
    'Add Insurance Panel': 'إضافة شركة تأمين',
    'Edit Insurance Panel': 'تعديل شركة تأمين',
    'City Name (EN) *': 'اسم المدينة (بالإنجليزية) *',
    'City Name (AR) *': 'اسم المدينة (بالعربية) *',
    'Country Code *': 'رمز الدولة *',
    'Sort Order *': 'ترتيب العرض *',
    'Locality Name (EN) *': 'اسم الحي (بالإنجليزية) *',
    'Locality Name (AR) *': 'اسم الحي (بالعربية) *',
    'Postal Code': 'الرمز البريدي',
    'Code *': 'الرمز *',
    'Category *': 'الفئة *',
    'Specialty Name (EN) *': 'اسم التخصص (بالإنجليزية) *',
    'Specialty Name (AR) *': 'اسم التخصص (بالعربية) *',
    'SubSpecialty Name (EN) *': 'اسم التخصص الفرعي (بالإنجليزية) *',
    'SubSpecialty Name (AR) *': 'اسم التخصص الفرعي (بالعربية) *',
    'Language Name (EN) *': 'اسم اللغة (بالإنجليزية) *',
    'Language Name (AR) *': 'اسم اللغة (بالعربية) *',
    'ISO Code *': 'رمز ISO *',
    'Provider Name (EN) *': 'اسم مزود التأمين (بالإنجليزية) *',
    'Provider Name (AR) *': 'اسم مزود التأمين (بالعربية) *',
    'Logo Upload': 'رفع الشعار',
    'Active Doctor Status': 'حالة الطبيب نشط',
    'Bio / Profile Summary': 'نبذة / ملخص الملف الشخصي',
    'Professional Title *': 'اللقب المهني *',
    'Doctor Full Name *': 'اسم الطبيب الكامل *',
    'MOH Registration # *': 'رقم الترخيص بوزارة الصحة *',
    'Years of Experience *': 'سنوات الخبرة *',
    'Consultation Fee (SAR) *': 'رسوم الكشف (ريال) *',
    // Patient Dashboard Browse Doctors
    'Browse Doctors': 'تصفح الأطباء',
    'Find and book consultations with top medical experts': 'ابحث واحجز استشارات مع أفضل الأطباء والخبراء',
    'Search Doctor Name': 'البحث باسم الطبيب',
    'Location / City': 'الموقع / المدينة',
    'All Cities': 'جميع المدن',
    'All Ratings': 'جميع التقييمات',
    'Spoken Language': 'اللغة المتحدث بها',
    'Min Experience': 'الحد الأدنى للخبرة',
    'Max Consultation Fee': 'الحد الأقصى لرسوم الكشف',
    'Reset Filters': 'إعادة ضبط الفلاتر',
    'General Practitioner': 'طبيب عام',
    'Experience:': 'الخبرة:',
    'View Profile': 'عرض الملف',
    'Book Consultation': 'حجز استشارة',
    'No Doctors Found': 'لم يتم العثور على أطباء',
    'Try adjusting your search query or reset filters to view all specialists.': 'جرب تعديل البحث أو إعادة ضبط الفلاتر لعرض جميع الأطباء.',
    'Show All Doctors': 'عرض جميع الأطباء',
    'Doctor Details': 'تفاصيل الطبيب',
    'MOH License': 'ترخيص وزارة الصحة',
    'Assigned Clinics & Locations': 'العيادات والمواقع المرتبطة',
    'Primary Clinic': 'العيادة الرئيسية',
    'Secondary': 'فرعية',
    'No qualifications recorded.': 'لا توجد مؤهلات مسجلة.',
    // Clinic Explorer
    'Search clinics...': 'البحث عن عيادة...',
    'No medical clinics found matching your current filter criteria.': 'لم يتم العثور على عيادات طبية تطابق معايير البحث الحالية.',
    'Select a Medical Clinic': 'اختر عيادة طبية',
    'Choose a clinic from the list on the left to view its active branches, operating schedules, and registered doctors roster.': 'اختر عيادة من القائمة على اليسار لمشاهدة فروعها النشطة، جدول العمل، وقائمة الأطباء المعتمدين.',
    'Back to Clinics List': 'العودة إلى قائمة العيادات',
    'Premier medical facility providing state of the art therapeutic and diagnostic healthcare solutions across the region.': 'منشأة طبية رائدة تقدم أحدث الحلول العلاجية والتشخيصية للرعاية الصحية في المنطقة.',
    'Select a Branch Location': 'اختر موقع الفرع',
    'No active clinic branch locations assigned.': 'لا تتوفر فروع نشطة لهذه العيادة.',
    'Primary': 'الرئيسي',
    'Availability & Hours': 'أوقات العمل وساعات التوفر',
    'No schedules listed for this branch.': 'لا تتوفر مواعيد مسجلة لهذا الفرع.',
    'No active specialist doctors assigned to this branch location.': 'لا يوجد أطباء أخصائيين مضافين لهذا الفرع.',
    'Select a Branch Location above': 'اختر موقع الفرع أعلاه',
    'Choose one of the active branch locations above to view its daily operating hours and list of available specialist doctors.': 'اختر أحد مواقع الفروع النشطة أعلاه لمشاهدة ساعات العمل اليومية وقائمة الأطباء الأخصائيين المتاحين.',
    'Closed': 'مغلق',
    'from': 'من',
    'Consultation Fee:': 'رسوم الكشف:',
    'Or choose another date:': 'أو اختر تاريخاً آخر:',
    'No open slots available for this doctor on the selected date.': 'لا تتوفر مواعيد مفتوحة لهذا الطبيب في التاريخ المحدد.',
    'Booked': 'محجوز',
    'Blocked': 'غير متاح',
    'Briefly describe your symptoms, medical concerns, or target goals for this visit...': 'صف باختصار الأعراض أو المخاوف الطبية لهذا الموعد...',
    // Auth additional
    'Welcome Back': 'مرحباً بك مجدداً',
    'Please enter your credentials to access your account': 'يرجى إدخال بيانات الاعتماد للوصول إلى حسابك',
    'Please enter a valid email address.': 'يرجى إدخال عنوان بريد إلكتروني صالح.',
    'Password must be at least 6 characters.': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
    'Sign In': 'تسجيل الدخول',
    'or': 'أو',
    'Continue with Google': 'المتابعة باستخدام Google',
    "Don't have an account?": "ليس لديك حساب؟",
    'Create an account': 'إنشاء حساب جديد',
    'Create an Account': 'إنشاء حساب جديد',
    'Join MedConsult to manage consultations and records seamlessly': 'انضم إلى MedConsult لإدارة الاستشارات والسجلات الطبية بسلاسة',
    'Full Name': 'الاسم الكامل',
    'Full name is required (min 2 characters).': 'الاسم الكامل مطلوب (على الأقل حرفين).',
    'Phone Number': 'رقم الهاتف',
    'Please enter a valid phone number.': 'يرجى إدخال رقم هاتف صالح.',
    'Preferred Language': 'اللغة المفضلة',
    'Already have an account?': 'لديك حساب بالفعل؟',
    'Symptoms placeholder': 'الأعراض أو سبب الاستشارة الطبية العام...',
    'MOH License:': 'ترخيص وزارة الصحة:',
    'Premier medical facility description': 'منشأة طبية رائدة تقدم رعاية استشارية شاملة.',
    'Active': 'نشط',
    'Select Type': 'اختر النوع',
    'Select Mode': 'اختر الوضع',
    // Patient Home
    'Hello,': 'أهلاً بك،',
    'Welcome!': 'مرحباً بك!',
    'Here is your general health summary and upcoming care schedule.': 'إليك ملخصك الصحي العام وجدول الرعاية الطبية القادمة.',
    'National ID:': 'الهوية الوطنية:',
    'Blood Type:': 'فصيلة الدم:',
    'Unknown': 'غير معروفة',
    'Welcome to MedConsult! Please complete your patient profile to unlock bookings and health records.': 'مرحباً بك في MedConsult! يرجى إكمال ملفك الشخصي لتفعيل الحجوزات والوصول للسجلات الطبية.',
    'Initialize Profile Now': 'إعداد الملف التعريفي الآن',
    'Find doctors, clinics & slots': 'البحث عن الأطباء، العيادات والمواعيد المتاحة',
    'Prescriptions, vitals & labs': 'الوصفات الطبية، المؤشرات الحيوية والمختبر',
    'Tele-consultations & advice': 'الاستشارات الطبية والتقارير الطبية عن بعد',
    'Upcoming Consultations': 'الاستشارات القادمة',
    'Book New Appointment': 'حجز موعد جديد',
    '+ Book New Appointment': '+ حجز موعد جديد',
    'Cancel': 'إلغاء الموعد',
    'No upcoming appointments booked.': 'لا توجد مواعيد استشارات قادمة محجوزة.',
    'Need to see a doctor? Book a new consultation slot in seconds.': 'هل تحتاج لزيارة طبيب؟ احجز موعداً جديداً في ثوانٍ معدودة.',
    'Cancel Appointment': 'إلغاء الاستشارة الطبية',
    'Are you sure you want to cancel your consultation with': 'هل أنت متأكد من رغبتك في إلغاء استشارتك مع',
    'on': 'بتاريخ',
    'Reason for Cancellation': 'سبب الإلغاء',
    'Cancel placeholder': 'يرجى توضيح سبب الإلغاء...',
    'Cancel error': 'حقل سبب الإلغاء مطلوب (بحد أقصى ٢٥٥ حرفاً).',
    'Go Back': 'الرجوع',
    'Confirm Cancellation': 'تأكيد إلغاء الموعد',
    'Message Doctor': 'مراسلة الطبيب',
    'View EMR Records': 'عرض السجلات الطبية',
    // Appointments Center
    'Appointment Center': 'مركز المواعيد',
    'Manage your upcoming consultations, view clinical session history, and modify scheduled visits.': 'إدارة استشاراتك القادمة، مشاهدة سجل الجلسات الطبية، وتعديل المواعيد المجدولة.',
    'Consultation Mode': 'طريقة الاستشارة',
    'From Date': 'من تاريخ',
    'To Date': 'إلى تاريخ',
    'Search Doctor': 'البحث عن طبيب',
    'Search by doctor/department...': 'البحث باسم الطبيب/القسم...',
    'Clear Filters': 'مسح الفلاتر',
    'Scheduled Slot': 'الموعد المجدول',
    'Clinic & Department': 'العيادة والقسم',
    'min': 'دقيقة',
    '🏢 In-Clinic': '🏢 في العيادة',
    '💻 Video Call': '💻 مكالمة فيديو',
    'View Details': 'عرض التفاصيل',
    'No appointments history matches the current filters.': 'لا يوجد سجل مواعيد يطابق الفلاتر الحالية.',
    'Showing page': 'عرض الصفحة',
    'of': 'من',
    'total records': 'إجمالي السجلات',
    'Appointment Specification Details': 'تفاصيل الموعد والمواصفات',
    'Scheduled Date & Time': 'التاريخ والوقت المجدول',
    'minutes duration': 'مدة بالدقائق',
    'Clinical Assignment': 'العيادة المسندة',
    'Consultation Details': 'تفاصيل الاستشارة',
    '🏢 In-Clinic Visit': '🏢 زيارة في العيادة',
    '💻 Video Call Session': '💻 جلسة مكالمة فيديو',
    'Reason for Consultation': 'سبب الاستشارة',
    'No specific reasons provided by the patient.': 'لم يتم تقديم أسباب محددة من المريض.',
    'Cancellation Information': 'معلومات الإلغاء',
    'Status:': 'الحالة:',
    'Reason': 'السبب',
    'No reason provided': 'لم يتم تقديم سبب',
    'Quick Shortcuts': 'اختصارات سريعة',
    'Write Review': 'كتابة تقييم',
    'Reschedule Visit': 'إعادة جدولة الموعد',
    'Go to Chat Session': 'الذهاب لمحادثة الاستشارة',
    'Close Details': 'إغلاق التفاصيل',
    'This action cannot be undone once confirmed.': 'لا يمكن التراجع عن هذا الإجراء بمجرد التأكيد.',
    'Reason for Cancellation *': 'سبب الإلغاء *',
    'Please tell us why you need to cancel this appointment': 'يرجى إخبارنا بطلب إلغاء هذا الموعد',
    'Reason is required (max 255 chars).': 'سبب الإلغاء مطلوب (الحد الأقصى 255 حرفاً).',
    'Reschedule Consultation': 'إعادة جدولة الاستشارة',
    'Select New Appointment Date *': 'اختر تاريخ الموعد الجديد *',
    'Confirm Reschedule': 'تأكيد إعادة الجدولة',
    'Processing...': 'جاري المعالجة...',
    'Rate Your Consultation': 'تقييم استشارتك',
    'Doctor Review': 'تقييم الطبيب',
    'Overall Doctor Rating (1-5) *': 'التقييم العام للطبيب (1-5) *',
    'Bedside *': 'التعامل واللياقة *',
    'Knowledge *': 'الخبرة والمعرفة *',
    'Wait Time *': 'وقت الانتظار *',
    'Clinic Review': 'تقييم العيادة',
    'Overall Clinic Rating (1-5) *': 'التقييم العام للعيادة (1-5) *',
    'Cleanliness *': 'النظافة والتعقيم *',
    'Staff *': 'طاقم العمل والخدمة *',
    'Written Feedback (Optional)': 'ملاحظات كتابية (اختياري)',
    'Share details of your experience...': 'شارك تفاصيل تجربتك مع الطبيب والعيادة...',
    'Max 2000 characters': 'الحد الأقصى 2000 حرف',
    'Submit this review anonymously': 'إرسال هذا التقييم مجهول الهوية',
    'Submit Feedback': 'إرسال التقييم',
    // Tele-Consultations
    'Book New Consultation': 'حجز استشارة جديدة',
    'No consultation records found.': 'لم يتم العثور على أي سجلات استشارة.',
    'Opened:': 'تاريخ الفتح:',
    'Consulting with': 'مع الطبيب',
    'Urgent': 'عاجل',
    'No messages yet. Send a message below to start the conversation.': 'لا توجد رسائل بعد. أرسل رسالة أدناه لبدء المحادثة.',
    'Type your message here...': 'اكتب رسالتك هنا...',
    'Send': 'إرسال',
    'This consultation has been closed.': 'تم إغلاق هذه الاستشارة.',
    'Rate Consultation': 'تقييم الاستشارة',
    'Select a consultation from the left list to view messages.': 'اختر استشارة من القائمة اليسرى لمشاهدة الرسائل.',
    'Book a Tele-Consultation': 'حجز استشارة عن بعد',
    'Select Doctor': 'اختر الطبيب',
    '-- Choose a Doctor --': '-- اختر الطبيب --',
    'Doctor selection is required.': 'حقل اختيار الطبيب مطلوب.',
    'Subject / Reason for Consultation': 'الموضوع / سبب الاستشارة',
    'Briefly describe your health concern': 'وصف مختصر للمشكلة الصحية',
    'Subject is required.': 'حقل الموضوع مطلوب.',
    'Mark as Urgent': 'تحديد كحالة عاجلة',
    'OPEN': 'مفتوح',
    'IN_PROGRESS': 'قيد المتابعة',
    'CLOSED': 'مغلق',
    // Health Metrics
    'Health Metrics & Medical History': 'المؤشرات الصحية والسجل الطبي',
    'Please initialize your General Patient Profile before entering your medical metrics.': 'يرجى إكمال ملف المريض الشخصي العام أولاً قبل تسجيل المؤشرات الطبية.',
    'Edit Metrics': 'تعديل المؤشرات',
    'Height (cm)': 'الطول (سم)',
    'Calculated BMI': 'مؤشر كتلة الجسم المحسوب (BMI)',
    'Smoking Status': 'حالة التدخين',
    'Alcohol Intake': 'استهلاك الكحول',
    'Surgical History': 'التاريخ الجراحي',
    'List any past surgeries...': 'اذكر أي عمليات جراحية سابقة...',
    'Family Medical History': 'التاريخ الطبي العائلي',
    'List hereditary conditions in your family...': 'اذكر الأمراض الوراثية في العائلة...',
    'Additional Notes': 'ملاحظات إضافية',
    'Other medical notes...': 'ملاحظات طبية أخرى...',
    'Save Changes': 'حفظ التغييرات',
    'Known Allergies': 'الحساسية المعروفة',
    'Add Allergy': 'إضافة حساسية',
    'Reaction:': 'رد الفعل التحسسي:',
    'No allergies listed on record.': 'لا توجد حالات حساسية مسجلة.',
    'Chronic Conditions': 'الأمراض المزمنة',
    'Add Condition': 'إضافة مرض مزمن',
    'ICD-10 Code:': 'رمز ICD-10:',
    'Diagnosed:': 'تاريخ التشخيص:',
    'No chronic conditions listed.': 'لا توجد أمراض مزمنة مسجلة.',
    'Add Known Allergy': 'إضافة حساسية معروفة',
    'Allergen Name': 'اسم المادة المسببة للحساسية',
    'E.g. Penicillin, Peanuts': 'مثل: البنسلين، الفول السوداني',
    'Allergy Type': 'نوع الحساسية',
    'Severity': 'درجة الشدة',
    'Allergic Reaction Details': 'تفاصيل الأعراض التحسسية',
    'E.g. Skin rashes, Anaphylaxis': 'مثل: طفح جلدي، ضيق تنفس',
    'Register Chronic Condition': 'تسجيل مرض مزمن',
    'Condition Name': 'اسم المرض / الحالة',
    'E.g. Diabetes Mellitus Type II': 'مثل: داء السكري من النوع الثاني',
    'ICD-10 Code': 'رمز ICD-10',
    'E.g. E11.9': 'مثل: E11.9',
    'Must be a valid ICD-10 format.': 'يجب إدخال صياغة ICD-10 صحيحة.',
    'Diagnosis Date': 'تاريخ التشخيص',
    'Condition Status': 'حالة المرض',
    'Notes': 'ملاحظات',
    'Relevant comments...': 'أضف أي ملاحظات ذات صلة...',
    // EMR additional
    'Registration Required': 'التسجيل مطلوب',
    'Please initialize your General Patient Profile before accessing your Electronic Medical Records (EMR).': 'يرجى إعداد ملف المريض الشخصي العام أولاً قبل محاولة الوصول إلى السجلات الطبية الإلكترونية (EMR).',
    'Setup Profile': 'إعداد الملف الشخصي',
    'Prescriptions & Adherence': 'الوصفات الطبية والالتزام بالعلاج',
    'Vitals History Log': 'سجل المؤشرات الحيوية',
    'Lab Test Reports': 'تقارير التحاليل والمختبر',
    'Prescription Reference:': 'مرجع الوصفة الطبية:',
    'Local Record': 'سجل محلي',
    'Issued:': 'تاريخ الإصدار:',
    'Valid Until:': 'صالحة حتى:',
    'ACTIVE': 'نشطة',
    'EXPIRED': 'منتهية صلاحيتها',
    'Diagnosis & Clinical Notes': 'التشخيص والملاحظات الطبية',
    'No diagnosis notes available.': 'لا توجد ملاحظات تشخيصية مسجلة.',
    'Prescribed Medications': 'الأدوية الموصوفة',
    'Dosage:': 'الجرعة:',
    'Route:': 'طريقة الاستخدام:',
    'Frequency:': 'التكرار:',
    'Duration:': 'المدة:',
    'Days': 'أيام',
    'Refills:': 'إعادة التعبئة:',
    'Used': 'مستخدمة',
    'Took Today': 'أخذته اليوم',
    'Latest:': 'آخر إجراء:',
    'Taken': 'تم أخذ الجرعة',
    'Skipped': 'تم تخطيه',
    'None recorded': 'لا يوجد سجل',
    'No prescriptions found on your EMR file.': 'لم يتم العثور على أي وصفات طبية مسجلة في ملفك الطبي.',
    'Vital Metrics History': 'سجل تتبع المؤشرات الحيوية',
    'Log New Vitals': 'تسجيل مؤشرات حيوية جديدة',
    'Blood Pressure:': 'ضغط الدم:',
    'Heart Rate:': 'معدل ضربات القلب:',
    'Blood Glucose:': 'مستوى السكر في الدم:',
    'Weight:': 'الوزن:',
    'O2 Saturation:': 'نسبة الأكسجين:',
    'No vitals records warning': 'لا توجد مؤشرات حيوية مسجلة. اضغط أعلاه لتسجيل أول مؤشر لك.',
    'Report:': 'التقرير:',
    'Date:': 'التاريخ:',
    'NORMAL': 'طبيعي',
    'ABNORMAL': 'غير طبيعي',
    'CRITICAL': 'حرج للغاية',
    'Doctors Annotations': 'ملاحظات وتوجيهات الطبيب',
    'No clinical annotation added.': 'لا توجد ملاحظات طبية مضافة.',
    'Attachment Document': 'المستند المرفق',
    'Download Attachment': 'تنزيل المرفق الطبي',
    'No lab report files warning': 'لا توجد تقارير تحاليل أو مختبر مرفوعة في ملفك.',
    'Log New Vital Entry': 'سجل مؤشراً حيوياً جديداً',
    'Systolic BP (mmHg)': 'ضغط الدم الانقباضي (mmHg)',
    'Diastolic BP (mmHg)': 'ضغط الدم الانبساطي (mmHg)',
    'Heart Rate (BPM)': 'نبضات القلب (BPM)',
    'Blood Glucose (mmol/L)': 'نسبة السكر في الدم (mmol/L)',
    'Weight (kg)': 'الوزن (كجم)',
    'Body Temp (°C)': 'درجة حرارة الجسم (مئوية)',
    'Log Notes': 'ملاحظات السجل',
    'Context, symptom notes placeholder': 'أضف تفاصيل الأعراض، السياق، الملاحظات...',
    'Record Vitals': 'حفظ القياسات الطبية',
    'PATIENT_APP': 'تطبيق المريض',
    'DOCTOR_ENTRY': 'إدخال الطبيب',
    'ORAL': 'فموي',
    'INTRAVENOUS': 'حقن وريدي',
    'Twice': 'مرتين يومياً',
    'Once': 'مرة يومياً',
    'Three times': 'ثلاث مرات يومياً',
    'Four times': 'أربع مرات يومياً',
    // Booking Wizard
    'Please initialize your General Patient Profile before booking a new appointment.': 'يرجى إكمال ملفك الشخصي العام أولاً قبل حجز موعد جديد.',
    'Schedule Your Consultation': 'جدولة استشارتك الطبية',
    'Select your preferred doctor, clinic branch, and appointment slot': 'اختر طبيبك المفضل، موقع العيادة، والموعد المناسب',
    'Follow the steps below to choose your doctor, date, and time slot': 'اتبع الخطوات أدناه لاختيار الطبيب، التاريخ، والموعد المناسب',
    'SA MOH Verified Network': 'شبكة معتمدة من وزارة الصحة 🇸🇦',
    'Doctor': 'الطبيب',
    'Clinic': 'العيادة',
    'Date': 'التاريخ',
    'Date & Time': 'التاريخ والوقت',
    'Slot': 'الموعد',
    'Confirm': 'تأكيد الحجز',
    'Step 1: Choose Specialist Doctor': 'الخطوة ١: اختر الطبيب الأخصائي',
    'Step 1: Choose Specialist Doctor *': 'الخطوة ١: اختر الطبيب الأخصائي *',
    'Browse our verified doctors panel and select a specialist to check clinic locations': 'تصفح أطبائنا المعتمدين واختر أخصائياً لمعاينة مواقع الفروع',
    'Search doctor name...': 'البحث باسم الطبيب...',
    'Active booking exists with this doctor': 'لديك حجز نشط سابق مع هذا الطبيب',
    'Yrs Exp': 'سنوات خبرة',
    '-- Select Specialist Doctor --': '-- اختر الطبيب الأخصائي --',
    'View Doctor Profile, Biography & Specialties': 'عرض الملف التعريفي للطبيب، السيرة الذاتية والتخصصات',
    'Step 2: Choose Clinic Location': 'الخطوة ٢: اختر موقع العيادة',
    'Step 2: Select Clinic Location *': 'الخطوة ٢: اختر موقع العيادة *',
    'Select from the branch locations where this doctor is currently practicing': 'اختر من مواقع الفروع التي يعمل بها هذا الطبيب حالياً',
    '-- Choose Clinic Location --': '-- اختر موقع العيادة --',
    'No Branches Registered': 'لا تتوفر فروع مسجلة',
    'This doctor is not assigned to any active clinic branch locations.': 'هذا الطبيب غير مخصص لأي موقع فرع نشط حالياً.',
    'No active clinic branch locations assigned to this doctor.': 'لا توجد مواقع فروع عيادات نشطة مخصصة لهذا الطبيب.',
    'Back to Doctors': 'العودة للأطباء',
    'Back': 'رجوع',
    'Next': 'التالي',
    'Step 3: Appointment Date & Time': 'الخطوة ٣: تاريخ ووقت الموعد',
    'Step 3: Choose Appointment Date *': 'الخطوة ٣: اختر تاريخ الموعد *',
    'Select a booking date to see available consultation time slots': 'اختر تاريخ الحجز لمشاهدة مواعيد الكشف المتاحة',
    'Select Date': 'اختر التاريخ',
    'Or choose any date:': 'أو اختر أي تاريخ:',
    'Available Slots': 'المواعيد المتاحة',
    'Step 4: Select Available Time Slot *': 'الخطوة ٤: اختر الموعد المتاح *',
    'No Time Slots Available': 'لا تتوفر مواعيد متاحة',
    'There are no open slots on the selected date. Try choosing another day.': 'لا تتوفر مواعيد مفتوحة في التاريخ المحدد. حاول اختيار يوم آخر.',
    'Step 4: Confirm & Book': 'الخطوة ٤: التأكيد والحجز',
    'Step 5: Confirm & Finalize Details': 'الخطوة ٥: تأكيد الحجز وتعبئة التفاصيل',
    'Provide appointment reason and choose session mode to book consultation': 'أدخل سبب الزيارة واختر نوع الجلسة لحجز الاستشارة',
    'Consultation Details Summary': 'ملخص تفاصيل الاستشارة',
    'Clinic Branch': 'فرع العيادة',
    'Consultation Fee': 'رسوم الاستشارة',
    'Session Mode *': 'نوع الجلسة *',
    'In Clinic': 'في العيادة',
    'Visit the doctor physically at the selected branch location.': 'زيارة الطبيب شخصياً في موقع الفرع المحدد.',
    'Virtual': 'استشارة افتراضية',
    'Consult online via text chat and attachments upload.': 'استشارة عبر الإنترنت من خلال المحادثة الكتابية ورفع المرفقات.',
    'Appointment Type *': 'نوع الموعد *',
    'New Patient': 'مريض جديد',
    'First consultation for this specific illness or checkup.': 'أول استشارة لهذا المرض أو الفحص المحدد.',
    'Follow Up': 'متابعة',
    'Routine diagnostic checkup or continuous test reviews.': 'فحص تشخيصي دوري أو مراجعة نتائج الفحوصات.',
    'Reason for Visit / Symptoms': 'سبب الزيارة / الأعراض',
    'Reason for Visit / Symptoms (Optional)': 'الأعراض أو سبب الزيارة (اختياري)',
    'Type short reasons or symptoms...': 'اكتب الأعراض أو سبب الزيارة باختصار...',
    'Confirm & Book Appointment': 'تأكيد وحجز الموعد',
    'NEW PATIENT': 'مريض جديد',
    'FOLLOW UP': 'متابعة',
    'CONSULTATION': 'استشارة',
    'EMERGENCY': 'حالة طارئة',
    'IN CLINIC': 'في العيادة',
    'VIDEO CONSULTATION': 'استشارة مرئية',
    'CHATTING': 'محادثة كتابية'
  }
};
