import { Injectable, signal, effect } from '@angular/core';

export type Lang = 'en' | 'ar';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  public currentLang = signal<Lang>((localStorage.getItem('preferredLang') as Lang) || 'en');

  constructor() {
    effect(() => {
      const lang = this.currentLang();
      localStorage.setItem('preferredLang', lang);
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = lang;

      if (lang === 'ar') {
        document.body.classList.add('rtl-mode');
        document.body.classList.remove('ltr-mode');
      } else {
        document.body.classList.add('ltr-mode');
        document.body.classList.remove('rtl-mode');
      }
    });
  }

  public setLanguage(lang: Lang): void {
    this.currentLang.set(lang);
  }

  public toggleLanguage(): void {
    this.currentLang.update(v => v === 'en' ? 'ar' : 'en');
  }

  public get isArabic(): boolean {
    return this.currentLang() === 'ar';
  }

  public translate<T>(enValue: T, arValue: T): T {
    return this.currentLang() === 'ar' ? arValue : enValue;
  }

  public instant(key: string): string {
    if (!key) return '';
    const cleanKey = key.trim();
    const trans = translations[this.currentLang()];
    return trans[cleanKey] !== undefined ? trans[cleanKey] : key;
  }
}

const translations: { [lang in Lang]: { [key: string]: string } } = {
  en: {
    // Database Specialties fixes
    'SFB': 'Family Medicine',
    'SPOFE': 'Sports Medicine',

    // Menu
    'Home Dashboard': 'Home Dashboard',
    'Clinics & Branches': 'Clinics & Branches',
    'My Appointments': 'My Appointments',
    'Medical Records (EMR)': 'Medical Records (EMR)',
    'Book Appointment': 'Book Appointment',
    'Tele-Consultations': 'Tele-Consultations',
    'My General Profile': 'My General Profile',
    'Personal Health Metrics': 'Personal Health Metrics',
    'Professional Profile': 'Professional Profile',
    'Consultation Schedule': 'Consultation Schedule',
    'My Consultations': 'My Consultations',
    'Case Rooms': 'Case Rooms',
    'Patient EMR Records': 'Patient EMR Records',
    'Availability & Slots': 'Availability & Slots',
    'Dashboard': 'Dashboard',
    'My Clinics': 'My Clinics',
    'Doctors Roster': 'Doctors Roster',
    'Global Configurations': 'Global Configurations',
    'Public Portal Home': 'Public Portal Home',
    'Logout': 'Logout',
    'View Public Portal': 'View Public Portal',
    'Dashboard Title': 'Dashboard',
    // Landing
    'Find a clinic': 'Find a clinic',
    'Platform features': 'Platform features',
    'Verified Network': 'Verified Network',
    'Go to Portal Dashboard →': 'Go to Portal Dashboard →',
    'Sign in': 'Sign in',
    'Sign up / List Clinic': 'Sign up / List Clinic',
    'MOH Eyebrow': '🇸🇦 Saudi Arabia & GCC Healthcare Portal',
    'Find a clinic.Connect with the right doctor.': 'Find a clinic. Connect with the right doctor.',
    'Search verified private clinics across Saudi Arabia. Browse doctors, filter by specialty, city, language, and availability — and book real appointments online.': 'Search verified private clinics across Saudi Arabia. Browse doctors, filter by specialty, city, language, and availability — and book real appointments online.',
    'Search clinics': 'Search clinics',
    'All Cities / Areas': '📍 All Cities / Areas',
    'Specialty:': 'Specialty:',
    'All': 'All',
    'All clinics verified by MOH': '✓ All clinics verified by MOH',
    'Real-time doctor schedules': '✓ real-time doctor schedules',
    'HIPAA-compliant system': '✓ HIPAA-compliant system',
    'Arabic & English': '✓ Arabic & English',
    'Verified Medical Clinics': 'Verified Medical Clinics',
    'Showing clinics': 'Showing clinics',
    'Sort by:': 'Sort by:',
    'Clinics List': 'Clinics List',
    'Filter Specialties': 'Filter Specialties',
    // Filters & Results
    'Filters & Refinements': 'Filters & Refinements',
    'Clear all': 'Clear all',
    'Doctor Availability': 'Doctor Availability',
    'Available Today Only': 'Available Today Only',
    'Medical Specialty': 'Medical Specialty',
    'City Location': 'City Location',
    'Minimum Rating': 'Minimum Rating',
    'Accepted Insurance': 'Accepted Insurance',
    '✅ MOH Verified': '✅ MOH Verified',
    '🟢 Active Facility': '🟢 Active Facility',
    'View Facility →': 'View Facility →',
    'specialist doctor(s) at this facility': 'specialist doctor(s) at this facility',
    'Years Exp': 'Years Exp',
    '🟢 Available today': '🟢 Available today',
    '🟡 Tomorrow': '🟡 Tomorrow',
    'Next Slot:': 'Next Slot:',
    'Book appointment': 'Book appointment',
    'Show fewer doctors': 'Show fewer doctors',
    'Show more doctors at this facility': 'Show more doctors at this facility',
    'No medical clinics found matching your current filter criteria. Click "Clear all" to reset filters.': 'No medical clinics found matching your current filter criteria. Click "Clear all" to reset filters.',
    // How it works
    'How it works': 'How it works',
    'Three steps to your appointment': 'Three steps to your appointment',
    'Search for a clinic': 'Search for a clinic',
    'Search by clinic name, city location, specialty or doctor. Filter by ratings, language, and insurance.': 'Search by clinic name, city location, specialty or doctor. Filter by ratings, language, and insurance.',
    'Choose your doctor': 'Choose your doctor',
    'Review doctor credentials, experience, spoken languages, and live open slots.': 'Review doctor credentials, experience, spoken languages, and live open slots.',
    'Select your preferred date & time slot. Confirm directly into the clinic system.': 'Select your preferred date & time slot. Confirm directly into the clinic system.',
    // Features
    '✦ Platform Features': '✦ Platform Features',
    'More than booking. A complete care platform.': 'More than booking. A complete care platform.',
    'Connected care across clinics, doctors, and patient records.': 'Connected care across clinics, doctors, and patient records.',
    'Secure Consultation Chat': 'Secure Consultation Chat',
    'Direct doctor-patient messaging with attachment support for medical records and prescriptions.': 'Direct doctor-patient messaging with attachment support for medical records and prescriptions.',
    'Case Discussion Rooms': 'Case Discussion Rooms',
    'Multidisciplinary case rooms enabling doctors across clinics to collaborate on patient care.': 'Multidisciplinary case rooms enabling doctors across clinics to collaborate on patient care.',
    'Lab Results & Test Reports': 'Lab Results & Test Reports',
    'Direct upload, preview, and download of clinical lab reports with reference range tracking.': 'Direct upload, preview, and download of clinical lab reports with reference range tracking.',
    'Digital Prescriptions': 'Digital Prescriptions',
    'Digital Prescriptions Body': 'Instant e-prescriptions issued directly by verified medical professionals.',
    'Unified Health Record': 'Unified Health Record',
    'Unified Health Record Body': 'Centralized medical history, vital signs, allergies, and chronic condition tracking.',
    'Privacy & Security': 'Privacy & Security',
    'Privacy & Security Body': 'Strict data governance aligned with Saudi MOH and HIPAA healthcare standards.',
    // Testimonials
    '💬 Verified Experience': '💬 Verified Experience',
    'Trusted across': 'Trusted across',
    'Saudi Arabia': 'Saudi Arabia',
    'Saudi MOH': 'Saudi MOH',
    'Verified License': 'Verified License',
    'Naphies': 'Naphies',
    'Interoperable': 'Interoperable',
    'HIPAA': 'HIPAA',
    'Compliant': 'Compliant',
    'Bilingual': 'Bilingual',
    // CTA & Footer
    '🚀 For Clinics & Doctors': '🚀 For Clinics & Doctors',
    'List your clinic.': 'List your clinic.',
    'Reach more patients.': 'Reach more patients.',
    'CTA subtitle': 'Join Saudi Arabia\'s verified healthcare provider platform with your branches and doctors live in 48 hours.',
    'Sign up / List clinic free →': 'Sign up / List clinic free →',
    'Sign in to portal': 'Sign in to portal',
    'Footer description': 'Connecting patients to verified clinics and specialist doctors across Saudi Arabia.',
    'For Patients': 'For Patients',
    'My health record': 'My health record',
    'For Clinics': 'For Clinics',
    'Clinic dashboard': 'Clinic dashboard',
    'System': 'System',
    'Saudi MOH Aligned': 'Saudi MOH Aligned',
    'HIPAA Compliant': 'HIPAA Compliant',
    'All rights reserved.': 'All rights reserved.',
    'Footer Bottom': 'HIPAA compliant · Naphies ready · Arabic & English',
    // Modals
    'Select Appointment Date *': 'Select Appointment Date *',
    'Available Slots for': 'Available Slots for',
    'No open slots warning': 'No open time slots found for this date. Please select another date.',
    'Appointment Type': 'Appointment Type',
    'Session Mode': 'Session Mode',
    'Reason for Visit (Optional)': 'Reason for Visit (Optional)',
    'Selected:': 'Selected:',
    'Processing Booking...': 'Processing Booking...',
    'Confirm Appointment Booking →': 'Confirm Appointment Booking →',
    'About Facility': 'About Facility',
    'Contact Information': 'Contact Information',
    'Facility Status': 'Facility Status',
    'Branches & Locations': 'Branches & Locations',
    'Close Facility Details': 'Close Facility Details',
    // General
    'Registration ID:': 'Registration ID:',
    'Spoken Languages': 'Spoken Languages',
    'No languages documented.': 'No languages documented.',
    'Professional Biography': 'Professional Biography',
    'No bio notes provided.': 'No bio notes provided.',
    'Associated Clinics & Locations': 'Associated Clinics & Locations',
    'Primary Location': 'Primary Location',
    'Department:': 'Department:',
    'Fee:': 'Fee:',
    'Joined:': 'Joined:',
    'No registered clinical locations assigned.': 'No registered clinical locations assigned.',
    'Academic Qualifications': 'Academic Qualifications',
    'No qualifications recorded on profile file.': 'No qualifications recorded on profile file.',
    'Year': 'Year',
    'Professional Credentials, Bio & Qualifications': 'Professional Credentials, Bio & Qualifications',
    'Bio & General Details': 'Bio & General Details',
    'Specialties': 'Specialties',
    'Qualifications': 'Qualifications',
    'Clinics': 'Clinics',
    'Save General Profile': 'Save General Profile',
    'Experience': 'Experience',
    'Years': 'Years',
    'Rating:': 'Rating:',
    'reviews': 'reviews',
    'Standard Fee:': 'Standard Fee:',
    'SAR': 'SAR',
    'Language *': 'Language *',
    'Proficiency *': 'Proficiency *',
    '+ Add Language': '+ Add Language',
    'Remove': 'Remove',
    'Language': 'Language',
    'Proficiency Level': 'Proficiency Level',
    'Actions': 'Actions',
    'No languages listed on your profile yet.': 'No languages listed on your profile yet.',
    'Degree Title': 'Degree Title',
    'University / Institution': 'University / Institution',
    'Country & Year': 'Country & Year',
    'Degree *': 'Degree *',
    'Institution / University *': 'Institution / University *',
    'Country *': 'Country *',
    'Year Obtained *': 'Year Obtained *',
    '+ Add Degree': '+ Add Degree',
    'No qualifications listed on your profile yet.': 'No qualifications listed on your profile yet.',
    // Auth additional
    'Welcome Back': 'Welcome Back',
    'Please enter your credentials to access your account': 'Please enter your credentials to access your account',
    'Please enter a valid email address.': 'Please enter a valid email address.',
    'Password must be at least 6 characters.': 'Password must be at least 6 characters.',
    'Sign In': 'Sign In',
    'or': 'or',
    'Continue with Google': 'Continue with Google',
    "Don't have an account?": "Don't have an account?",
    'Create an account': 'Create an account',
    'Create an Account': 'Create an Account',
    'Join MedConsult to manage consultations and records seamlessly': 'Join MedConsult to manage consultations and records seamlessly',
    'Full Name': 'Full Name',
    'Full name is required (min 2 characters).': 'Full name is required (min 2 characters).',
    'Phone Number': 'Phone Number',
    'Please enter a valid phone number.': 'Please enter a valid phone number.',
    'Preferred Language': 'Preferred Language',
    'Already have an account?': 'Already have an account?',
    'Symptoms placeholder': 'Symptoms or general consultation reason...',
    'MOH License:': 'MOH License:',
    'Premier medical facility description': 'Premier medical facility providing comprehensive specialist care.',
    'Active': 'Active',
    'Select Type': 'Select Type',
    'Select Mode': 'Select Mode',
    // Patient Home
    'Hello,': 'Hello,',
    'Welcome!': 'Welcome!',
    'Here is your general health summary and upcoming care schedule.': 'Here is your general health summary and upcoming care schedule.',
    'National ID:': 'National ID:',
    'Blood Type:': 'Blood Type:',
    'Unknown': 'Unknown',
    'Welcome to MedConsult! Please complete your patient profile to unlock bookings and health records.': 'Welcome to MedConsult! Please complete your patient profile to unlock bookings and health records.',
    'Initialize Profile Now': 'Initialize Profile Now',
    'Find doctors, clinics & slots': 'Find doctors, clinics & slots',
    'Prescriptions, vitals & labs': 'Prescriptions, vitals & labs',
    'Tele-consultations & advice': 'Tele-consultations & advice',
    'Upcoming Consultations': 'Upcoming Consultations',
    'Book New Appointment': 'Book New Appointment',
    '+ Book New Appointment': '+ Book New Appointment',
    'Cancel': 'Cancel',
    'No upcoming appointments booked.': 'No upcoming appointments booked.',
    'Need to see a doctor? Book a new consultation slot in seconds.': 'Need to see a doctor? Book a new consultation slot in seconds.',
    'Cancel Appointment': 'Cancel Appointment',
    'Are you sure you want to cancel your consultation with': 'Are you sure you want to cancel your consultation with',
    'on': 'on',
    'Reason for Cancellation': 'Reason for Cancellation',
    'Cancel placeholder': 'Please explain why you are cancelling...',
    'Cancel error': 'Cancellation reason is required (max 255 chars).',
    'Go Back': 'Go Back',
    'Confirm Cancellation': 'Confirm Cancellation',
    'Message Doctor': 'Message Doctor',
    'View EMR Records': 'View EMR Records',
    // EMR additional
    'Registration Required': 'Registration Required',
    'Please initialize your General Patient Profile before accessing your Electronic Medical Records (EMR).': 'Please initialize your General Patient Profile before accessing your Electronic Medical Records (EMR).',
    'Setup Profile': 'Setup Profile',
    'Prescriptions & Adherence': 'Prescriptions & Adherence',
    'Vitals History Log': 'Vitals History Log',
    'Lab Test Reports': 'Lab Test Reports',
    'Prescription Reference:': 'Prescription Reference:',
    'Local Record': 'Local Record',
    'Issued:': 'Issued:',
    'Valid Until:': 'Valid Until:',
    'ACTIVE': 'ACTIVE',
    'EXPIRED': 'EXPIRED',
    'Diagnosis & Clinical Notes': 'Diagnosis & Clinical Notes',
    'No diagnosis notes available.': 'No diagnosis notes available.',
    'Prescribed Medications': 'Prescribed Medications',
    'Dosage:': 'Dosage:',
    'Route:': 'Route:',
    'Frequency:': 'Frequency:',
    'Duration:': 'Duration:',
    'Days': 'Days',
    'Refills:': 'Refills:',
    'Used': 'Used',
    'Took Today': 'Took Today',
    'Latest:': 'Latest:',
    'Taken': 'Taken',
    'Skipped': 'Skipped',
    'None recorded': 'None recorded',
    'No prescriptions found on your EMR file.': 'No prescriptions found on your EMR file.',
    'Vital Metrics History': 'Vital Metrics History',
    'Log New Vitals': 'Log New Vitals',
    'Blood Pressure:': 'Blood Pressure:',
    'Heart Rate:': 'Heart Rate:',
    'Blood Glucose:': 'Blood Glucose:',
    'Weight:': 'Weight:',
    'O2 Saturation:': 'O2 Saturation:',
    'No vitals records warning': 'No vitals records listed. Click above to log your first metric.',
    'Report:': 'Report:',
    'Date:': 'Date:',
    'NORMAL': 'NORMAL',
    'ABNORMAL': 'ABNORMAL',
    'CRITICAL': 'CRITICAL',
    'Doctors Annotations': 'Doctor\'s Annotations',
    'No clinical annotation added.': 'No clinical annotation added.',
    'Attachment Document': 'Attachment Document',
    'Download Attachment': 'Download Attachment',
    'No lab report files warning': 'No lab report files uploaded on your file.',
    'Log New Vital Entry': 'Log New Vital Entry',
    'Systolic BP (mmHg)': 'Systolic BP (mmHg)',
    'Diastolic BP (mmHg)': 'Diastolic BP (mmHg)',
    'Heart Rate (BPM)': 'Heart Rate (BPM)',
    'Blood Glucose (mmol/L)': 'Blood Glucose (mmol/L)',
    'Weight (kg)': 'Weight (kg)',
    'Body Temp (°C)': 'Body Temp (°C)',
    'Log Notes': 'Log Notes',
    'Context, symptom notes placeholder': 'Context, symptom notes...',
    'Record Vitals': 'Record Vitals',
    'PATIENT_APP': 'Patient App',
    'DOCTOR_ENTRY': 'Doctor Entry',
    'ORAL': 'Oral',
    'INTRAVENOUS': 'Intravenous',
    'Twice': 'Twice',
    'Once': 'Once',
    'Three times': 'Three times',
    'Four times': 'Four times',
    // Booking Wizard
    'Please initialize your General Patient Profile before booking a new appointment.': 'Please initialize your General Patient Profile before booking a new appointment.',
    'Schedule Your Consultation': 'Schedule Your Consultation',
    'Follow the steps below to choose your doctor, date, and time slot': 'Follow the steps below to choose your doctor, date, and time slot',
    'SA MOH Verified Network': 'SA MOH Verified Network',
    'Doctor': 'Doctor',
    'Clinic': 'Clinic',
    'Date': 'Date',
    'Slot': 'Slot',
    'Confirm': 'Confirm',
    'Step 1: Choose Specialist Doctor *': 'Step 1: Choose Specialist Doctor *',
    '-- Select Specialist Doctor --': '-- Select Specialist Doctor --',
    'View Doctor Profile, Biography & Specialties': 'View Doctor Profile, Biography & Specialties',
    'Step 2: Select Clinic Location *': 'Step 2: Select Clinic Location *',
    '-- Choose Clinic Location --': '-- Choose Clinic Location --',
    'No active clinic branch locations assigned to this doctor.': 'No active clinic branch locations assigned to this doctor.',
    'Step 3: Choose Appointment Date *': 'Step 3: Choose Appointment Date *',
    'Step 4: Select Available Time Slot *': 'Step 4: Select Available Time Slot *',
    'Step 5: Confirm & Finalize Details': 'Step 5: Confirm & Finalize Details',
    'Appointment Type *': 'Appointment Type *',
    'Session Mode *': 'Session Mode *',
    'Reason for Visit / Symptoms (Optional)': 'Reason for Visit / Symptoms (Optional)',
    'Confirm & Book Appointment': 'Confirm & Book Appointment',
    'NEW PATIENT': 'New Patient',
    'FOLLOW UP': 'Follow Up',
    'CONSULTATION': 'Consultation',
    'EMERGENCY': 'Emergency',
    'IN CLINIC': 'In Clinic',
    'VIDEO CONSULTATION': 'Video Consultation',
    'CHATTING': 'Chatting'
  },
  ar: {
    // Database Specialties fixes
    'SFB': 'طب الأسرة',
    'SPOFE': 'الطب الرياضي',

    // Menu
    'Home Dashboard': 'لوحة التحكم الرئيسية',
    'Clinics & Branches': 'العيادات والفروع',
    'My Appointments': 'مواعيدي',
    'Medical Records (EMR)': 'السجلات الطبية (EMR)',
    'Book Appointment': 'حجز موعد',
    'Tele-Consultations': 'الاستشارات الطبية',
    'My General Profile': 'الملف الشخصي العام',
    'Personal Health Metrics': 'المؤشرات الصحية الشخصية',
    'Professional Profile': 'الملف المهني',
    'Consultation Schedule': 'جدول الاستشارات',
    'My Consultations': 'استشاراتي',
    'Case Rooms': 'غرف الحالات',
    'Patient EMR Records': 'سجلات المرضى (EMR)',
    'Availability & Slots': 'المواعيد الشاغرة',
    'Dashboard': 'لوحة التحكم',
    'My Clinics': 'عياداتي',
    'Doctors Roster': 'قائمة الأطباء',
    'Global Configurations': 'الإعدادات العامة',
    'Public Portal Home': 'البوابة العامة',
    'Logout': 'تسجيل الخروج',
    'View Public Portal': 'عرض البوابة العامة',
    'Dashboard Title': 'لوحة التحكم',
    // Landing
    'Find a clinic': 'البحث عن عيادة',
    'Platform features': 'مزايا المنصة',
    'Verified Network': 'الشبكة المعتمدة',
    'Go to Portal Dashboard →': 'الانتقال للوحة التحكم ←',
    'Sign in': 'تسجيل الدخول',
    'Sign up / List Clinic': 'تسجيل جديد / إضافة عيادة',
    'MOH Eyebrow': '🇸🇦 بوابة الرعاية الصحية المعتمدة في المملكة والخليج',
    'Find a clinic.Connect with the right doctor.': 'ابحث عن عيادة. تواصل مع الطبيب المناسب.',
    'Search verified private clinics across Saudi Arabia. Browse doctors, filter by specialty, city, language, and availability — and book real appointments online.': 'ابحث في العيادات الخاصة المعتمدة في المملكة العربية السعودية. تصفح الأطباء، ورشح حسب التخصص، المدينة، اللغة، والتوفر - واحجز مواعيدك الطبية مباشرة عبر الإنترنت.',
    'Search clinics': 'البحث عن عيادات',
    'All Cities / Areas': '📍 جميع المدن / المناطق',
    'Specialty:': 'التخصص:',
    'All': 'الكل',
    'All clinics verified by MOH': '✓ جميع العيادات معتمدة من وزارة الصحة',
    'Real-time doctor schedules': '✓ مواعيد حقيقية ومباشرة للأطباء',
    'HIPAA-compliant system': '✓ نظام متوافق مع معايير HIPAA',
    'Arabic & English': '✓ باللغتين العربية والإنجليزية',
    'Verified Medical Clinics': 'العيادات الطبية المعتمدة',
    'Showing clinics': 'عرض العيادات من قاعدة البيانات',
    'Sort by:': 'ترتيب حسب:',
    'Clinics List': 'قائمة العيادات',
    'Filter Specialties': 'تصفية التخصصات',
    // Filters & Results
    'Filters & Refinements': 'التصفية والخيارات',
    'Clear all': 'مسح الكل',
    'Doctor Availability': 'توفر الطبيب',
    'Available Today Only': 'متاح اليوم فقط',
    'Medical Specialty': 'التخصص الطبي',
    'City Location': 'المدينة / المنطقة',
    'Minimum Rating': 'الحد الأدنى للتقييم',
    'Accepted Insurance': 'التأمين المقبول',
    '✅ MOH Verified': '✅ معتمد من وزارة الصحة',
    '🟢 Active Facility': '🟢 منشأة نشطة',
    'View Facility →': 'عرض التفاصيل ←',
    'specialist doctor(s) at this facility': 'أطباء أخصائيين في هذه المنشأة',
    'Years Exp': 'سنة خبرة',
    '🟢 Available today': '🟢 متاح اليوم',
    '🟡 Tomorrow': '🟡 متاح غداً',
    'Next Slot:': 'الموعد القادم:',
    'Book appointment': 'حجز موعد',
    'Show fewer doctors': 'عرض أطباء أقل',
    'Show more doctors at this facility': 'عرض المزيد من الأطباء في هذه المنشأة',
    'No medical clinics found matching your current filter criteria. Click "Clear all" to reset filters.': 'لم يتم العثور على أي عيادات مطابقة لمعايير البحث الحالية. اضغط على "مسح الكل" لإعادة ضبط التصفية.',
    // How it works
    'How it works': 'طريقة العمل',
    'Three steps to your appointment': 'ثلاث خطوات لحجز موعدك',
    'Search for a clinic': 'البحث عن عيادة',
    'Search by clinic name, city location, specialty or doctor. Filter by ratings, language, and insurance.': 'البحث عن طريق اسم العيادة، المدينة، التخصص أو الطبيب. والتصفية حسب التقييمات، اللغات، والتأمين.',
    'Choose your doctor': 'اختيار طبيبك',
    'Review doctor credentials, experience, spoken languages, and live open slots.': 'مراجعة مؤهلات الطبيب، سنوات الخبرة، اللغات التي يتحدث بها، والمواعيد المتاحة مباشرة.',
    'Select your preferred date & time slot. Confirm directly into the clinic system.': 'حدد التاريخ ووقت الموعد المفضلين لديك. وأكد الحجز مباشرة في نظام العيادة.',
    // Features
    '✦ Platform Features': '✦ مزايا المنصة',
    'More than booking. A complete care platform.': 'أكثر من مجرد حجز. منصة رعاية صحية متكاملة.',
    'Connected care across clinics, doctors, and patient records.': 'رعاية متصلة تربط العيادات والأطباء والسجلات الطبية للمرضى.',
    'Secure Consultation Chat': 'دردشة استشارات آمنة',
    'Direct doctor-patient messaging with attachment support for medical records and prescriptions.': 'مراسلة مباشرة بين الطبيب والمريض مع إمكانية إرفاق الملفات الطبية والوصفات.',
    'Case Discussion Rooms': 'غرف مناقشة الحالات',
    'Multidisciplinary case rooms enabling doctors across clinics to collaborate on patient care.': 'غرف استشارية مشتركة تمكن الأطباء من مختلف العيادات من التعاون في رعاية المرضى.',
    'Lab Results & Test Reports': 'نتائج المختبر والتقارير الطبية',
    'Direct upload, preview, and download of clinical lab reports with reference range tracking.': 'رفع ومعاينة وتنزيل تقارير المختبر الطبية مباشرة مع تتبع النسب المرجعية.',
    'Digital Prescriptions': 'الوصفات الطبية الرقمية',
    'Digital Prescriptions Body': 'وصفات طبية إلكترونية فورية تصدر مباشرة من كوادر طبية معتمدة.',
    'Unified Health Record': 'سجل صحي موحد',
    'Unified Health Record Body': 'ملف طبي مركزي يحتوي على التاريخ المرضي، المؤشرات الحيوية، الحساسية، والأمراض المزمنة.',
    'Privacy & Security': 'الخصوصية والأمان',
    'Privacy & Security Body': 'حوكمة صارمة للبيانات تتماشى مع معايير وزارة الصحة السعودية ومعايير HIPAA الصحية.',
    // Testimonials
    '💬 Verified Experience': '💬 تجربة معتمدة',
    'Trusted across': 'موثوق في جميع أنحاء',
    'Saudi Arabia': 'المملكة العربية السعودية',
    'Saudi MOH': 'وزارة الصحة السعودية',
    'Verified License': 'ترخيص معتمد',
    'Naphies': 'نفيس',
    'Interoperable': 'ربط متكامل',
    'HIPAA': 'HIPAA',
    'Compliant': 'متوافق بالكامل',
    'Bilingual': 'ثنائي اللغة',
    // CTA & Footer
    '🚀 For Clinics & Doctors': '🚀 للعيادات والأطباء',
    'List your clinic.': 'سجل عيادتك.',
    'Reach more patients.': 'تواصل مع مرضى أكثر.',
    'CTA subtitle': 'انضم إلى منصة مزودي الرعاية الصحية المعتمدة في السعودية مع تفعيل فروعك وأطبائك خلال ٤٨ ساعة.',
    'Sign up / List clinic free →': 'تسجيل جديد / أضف عيادتك مجاناً ←',
    'Sign in to portal': 'تسجيل دخول البوابة',
    'Footer description': 'ربط المرضى بالعيادات المعتمدة والأطباء الأخصائيين في المملكة العربية السعودية.',
    'For Patients': 'للمرضى',
    'My health record': 'سجلي الصحي',
    'For Clinics': 'للعيادات',
    'Clinic dashboard': 'لوحة تحكم العيادة',
    'System': 'النظام',
    'Saudi MOH Aligned': 'متوافق مع وزارة الصحة',
    'HIPAA Compliant': 'متوافق مع معايير HIPAA',
    'All rights reserved.': 'جميع الحقوق محفوظة.',
    'Footer Bottom': 'متوافق مع HIPAA · جاهز للربط مع نفيس · باللغتين العربية والإنجليزية',
    // Modals
    'Select Appointment Date *': 'اختر تاريخ الموعد *',
    'Available Slots for': 'المواعيد المتاحة لتاريخ',
    'No open slots warning': 'لا توجد مواعيد متاحة في هذا اليوم. يرجى اختيار تاريخ آخر.',
    'Appointment Type': 'نوع الموعد',
    'Session Mode': 'نوع الجلسة',
    'Reason for Visit (Optional)': 'سبب الزيارة (اختياري)',
    'Selected:': 'المحدد:',
    'Processing Booking...': 'جاري إتمام الحجز...',
    'Confirm Appointment Booking →': 'تأكيد حجز الموعد ←',
    'About Facility': 'حول المنشأة',
    'Contact Information': 'معلومات الاتصال',
    'Facility Status': 'حالة المنشأة',
    'Branches & Locations': 'الفروع والمواقع',
    'Close Facility Details': 'إغلاق تفاصيل المنشأة',
    // General
    'Registration ID:': 'رقم التسجيل:',
    'Spoken Languages': 'اللغات المتحدثة',
    'No languages documented.': 'لا توجد لغات مسجلة.',
    'Professional Biography': 'السيرة المهنية',
    'No bio notes provided.': 'لا توجد نبذة تعريفية.',
    'Associated Clinics & Locations': 'العيادات والمواقع التابعة',
    'Primary Location': 'الموقع الرئيسي',
    'Department:': 'القسم:',
    'Fee:': 'رسوم الكشف:',
    'Joined:': 'تاريخ الانضمام:',
    'No registered clinical locations assigned.': 'لا توجد مواقع عيادات مسجلة بعد.',
    'Academic Qualifications': 'المؤهلات العلمية الأكاديمية',
    'No qualifications recorded on profile file.': 'لا توجد مؤهلات مسجلة في الملف الشخصي.',
    'Year': 'سنة',
    'Professional Credentials, Bio & Qualifications': 'الاعتمادات المهنية، السيرة الذاتية والمؤهلات',
    'Bio & General Details': 'السيرة الذاتية والتفاصيل العامة',
    'Specialties': 'التخصصات',
    'Qualifications': 'المؤهلات',
    'Clinics': 'العيادات التابعة',
    'Save General Profile': 'حفظ الملف التعريفي العام',
    'Experience': 'الخبرة',
    'Years': 'سنوات',
    'Rating:': 'التقييم:',
    'reviews': 'تقييمات',
    'Standard Fee:': 'الرسوم القياسية:',
    'SAR': 'ريال سعودي',
    'Language *': 'اللغة *',
    'Proficiency *': 'مستوى الإتقان *',
    '+ Add Language': '+ إضافة لغة',
    'Remove': 'حذف',
    'Language': 'اللغة',
    'Proficiency Level': 'مستوى الإتقان',
    'Actions': 'العمليات',
    'No languages listed on your profile yet.': 'لم يتم إضافة أي لغات لملفك الشخصي بعد.',
    'Degree Title': 'عنوان الدرجة',
    'University / Institution': 'الجامعة / المؤسسة',
    'Country & Year': 'البلد والسنة',
    'Degree *': 'الدرجة العلمية *',
    'Institution / University *': 'المؤسسة / الجامعة *',
    'Country *': 'البلد *',
    'Year Obtained *': 'سنة الحصول عليها *',
    '+ Add Degree': '+ إضافة درجة',
    'No qualifications listed on your profile yet.': 'لم يتم إضافة أي مؤهلات لملفك الشخصي بعد.',
    // Auth additional
    'Welcome Back': 'مرحباً بك مجدداً',
    'Please enter your credentials to access your account': 'يرجى إدخال بيانات الاعتماد للوصول إلى حسابك',
    'Please enter a valid email address.': 'يرجى إدخال عنوان بريد إلكتروني صالح.',
    'Password must be at least 6 characters.': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
    'Sign In': 'تسجيل الدخول',
    'or': 'أو',
    'Continue with Google': 'المتابعة باستخدام Google',
    "Don't have an account?": "ليس لديك حساب؟",
    'Create an account': 'إنشاء حساب جديد',
    'Create an Account': 'إنشاء حساب جديد',
    'Join MedConsult to manage consultations and records seamlessly': 'انضم إلى MedConsult لإدارة الاستشارات والسجلات الطبية بسلاسة',
    'Full Name': 'الاسم الكامل',
    'Full name is required (min 2 characters).': 'الاسم الكامل مطلوب (على الأقل حرفين).',
    'Phone Number': 'رقم الهاتف',
    'Please enter a valid phone number.': 'يرجى إدخال رقم هاتف صالح.',
    'Preferred Language': 'اللغة المفضلة',
    'Already have an account?': 'لديك حساب بالفعل؟',
    'Symptoms placeholder': 'الأعراض أو سبب الاستشارة الطبية العام...',
    'MOH License:': 'ترخيص وزارة الصحة:',
    'Premier medical facility description': 'منشأة طبية رائدة تقدم رعاية استشارية شاملة.',
    'Active': 'نشط',
    'Select Type': 'اختر النوع',
    'Select Mode': 'اختر الوضع',
    // Patient Home
    'Hello,': 'أهلاً بك،',
    'Welcome!': 'مرحباً بك!',
    'Here is your general health summary and upcoming care schedule.': 'إليك ملخصك الصحي العام وجدول الرعاية الطبية القادمة.',
    'National ID:': 'الهوية الوطنية:',
    'Blood Type:': 'فصيلة الدم:',
    'Unknown': 'غير معروفة',
    'Welcome to MedConsult! Please complete your patient profile to unlock bookings and health records.': 'مرحباً بك في MedConsult! يرجى إكمال ملفك الشخصي لتفعيل الحجوزات والوصول للسجلات الطبية.',
    'Initialize Profile Now': 'إعداد الملف التعريفي الآن',
    'Find doctors, clinics & slots': 'البحث عن الأطباء، العيادات والمواعيد المتاحة',
    'Prescriptions, vitals & labs': 'الوصفات الطبية، المؤشرات الحيوية والمختبر',
    'Tele-consultations & advice': 'الاستشارات الطبية والتقارير الطبية عن بعد',
    'Upcoming Consultations': 'الاستشارات القادمة',
    'Book New Appointment': 'حجز موعد جديد',
    '+ Book New Appointment': '+ حجز موعد جديد',
    'Cancel': 'إلغاء الموعد',
    'No upcoming appointments booked.': 'لا توجد مواعيد استشارات قادمة محجوزة.',
    'Need to see a doctor? Book a new consultation slot in seconds.': 'هل تحتاج لزيارة طبيب؟ احجز موعداً جديداً في ثوانٍ معدودة.',
    'Cancel Appointment': 'إلغاء الاستشارة الطبية',
    'Are you sure you want to cancel your consultation with': 'هل أنت متأكد من رغبتك في إلغاء استشارتك مع',
    'on': 'بتاريخ',
    'Reason for Cancellation': 'سبب الإلغاء',
    'Cancel placeholder': 'يرجى توضيح سبب الإلغاء...',
    'Cancel error': 'حقل سبب الإلغاء مطلوب (بحد أقصى ٢٥٥ حرفاً).',
    'Go Back': 'الرجوع',
    'Confirm Cancellation': 'تأكيد إلغاء الموعد',
    'Message Doctor': 'مراسلة الطبيب',
    'View EMR Records': 'عرض السجلات الطبية',
    // EMR additional
    'Registration Required': 'التسجيل مطلوب',
    'Please initialize your General Patient Profile before accessing your Electronic Medical Records (EMR).': 'يرجى إعداد ملف المريض الشخصي العام أولاً قبل محاولة الوصول إلى السجلات الطبية الإلكترونية (EMR).',
    'Setup Profile': 'إعداد الملف الشخصي',
    'Prescriptions & Adherence': 'الوصفات الطبية والالتزام بالعلاج',
    'Vitals History Log': 'سجل المؤشرات الحيوية',
    'Lab Test Reports': 'تقارير التحاليل والمختبر',
    'Prescription Reference:': 'مرجع الوصفة الطبية:',
    'Local Record': 'سجل محلي',
    'Issued:': 'تاريخ الإصدار:',
    'Valid Until:': 'صالحة حتى:',
    'ACTIVE': 'نشطة',
    'EXPIRED': 'منتهية صلاحيتها',
    'Diagnosis & Clinical Notes': 'التشخيص والملاحظات الطبية',
    'No diagnosis notes available.': 'لا توجد ملاحظات تشخيصية مسجلة.',
    'Prescribed Medications': 'الأدوية الموصوفة',
    'Dosage:': 'الجرعة:',
    'Route:': 'طريقة الاستخدام:',
    'Frequency:': 'التكرار:',
    'Duration:': 'المدة:',
    'Days': 'أيام',
    'Refills:': 'إعادة التعبئة:',
    'Used': 'مستخدمة',
    'Took Today': 'أخذته اليوم',
    'Latest:': 'آخر إجراء:',
    'Taken': 'تم أخذ الجرعة',
    'Skipped': 'تم تخطيه',
    'None recorded': 'لا يوجد سجل',
    'No prescriptions found on your EMR file.': 'لم يتم العثور على أي وصفات طبية مسجلة في ملفك الطبي.',
    'Vital Metrics History': 'سجل تتبع المؤشرات الحيوية',
    'Log New Vitals': 'تسجيل مؤشرات حيوية جديدة',
    'Blood Pressure:': 'ضغط الدم:',
    'Heart Rate:': 'معدل ضربات القلب:',
    'Blood Glucose:': 'مستوى السكر في الدم:',
    'Weight:': 'الوزن:',
    'O2 Saturation:': 'نسبة الأكسجين:',
    'No vitals records warning': 'لا توجد مؤشرات حيوية مسجلة. اضغط أعلاه لتسجيل أول مؤشر لك.',
    'Report:': 'التقرير:',
    'Date:': 'التاريخ:',
    'NORMAL': 'طبيعي',
    'ABNORMAL': 'غير طبيعي',
    'CRITICAL': 'حرج للغاية',
    'Doctors Annotations': 'ملاحظات وتوجيهات الطبيب',
    'No clinical annotation added.': 'لا توجد ملاحظات طبية مضافة.',
    'Attachment Document': 'المستند المرفق',
    'Download Attachment': 'تنزيل المرفق الطبي',
    'No lab report files warning': 'لا توجد تقارير تحاليل أو مختبر مرفوعة في ملفك.',
    'Log New Vital Entry': 'سجل مؤشراً حيوياً جديداً',
    'Systolic BP (mmHg)': 'ضغط الدم الانقباضي (mmHg)',
    'Diastolic BP (mmHg)': 'ضغط الدم الانبساطي (mmHg)',
    'Heart Rate (BPM)': 'نبضات القلب (BPM)',
    'Blood Glucose (mmol/L)': 'نسبة السكر في الدم (mmol/L)',
    'Weight (kg)': 'الوزن (كجم)',
    'Body Temp (°C)': 'درجة حرارة الجسم (مئوية)',
    'Log Notes': 'ملاحظات السجل',
    'Context, symptom notes placeholder': 'أضف تفاصيل الأعراض، السياق، الملاحظات...',
    'Record Vitals': 'حفظ القياسات الطبية',
    'PATIENT_APP': 'تطبيق المريض',
    'DOCTOR_ENTRY': 'إدخال الطبيب',
    'ORAL': 'فموي',
    'INTRAVENOUS': 'حقن وريدي',
    'Twice': 'مرتين يومياً',
    'Once': 'مرة يومياً',
    'Three times': 'ثلاث مرات يومياً',
    'Four times': 'أربع مرات يومياً',
    // Booking Wizard
    'Please initialize your General Patient Profile before booking a new appointment.': 'يرجى إكمال ملفك الشخصي العام أولاً قبل حجز موعد جديد.',
    'Schedule Your Consultation': 'جدولة استشارتك الطبية',
    'Follow the steps below to choose your doctor, date, and time slot': 'اتبع الخطوات أدناه لاختيار الطبيب، التاريخ، والموعد المناسب',
    'SA MOH Verified Network': 'شبكة معتمدة من وزارة الصحة 🇸🇦',
    'Doctor': 'الطبيب',
    'Clinic': 'العيادة',
    'Date': 'التاريخ',
    'Slot': 'الموعد',
    'Confirm': 'تأكيد الحجز',
    'Step 1: Choose Specialist Doctor *': 'الخطوة ١: اختر الطبيب الأخصائي *',
    '-- Select Specialist Doctor --': '-- اختر الطبيب الأخصائي --',
    'View Doctor Profile, Biography & Specialties': 'عرض الملف التعريفي للطبيب، السيرة الذاتية والتخصصات',
    'Step 2: Select Clinic Location *': 'الخطوة ٢: اختر موقع العيادة *',
    '-- Choose Clinic Location --': '-- اختر موقع العيادة --',
    'No active clinic branch locations assigned to this doctor.': 'لا توجد مواقع فروع عيادات نشطة مخصصة لهذا الطبيب.',
    'Step 3: Choose Appointment Date *': 'الخطوة ٣: اختر تاريخ الموعد *',
    'Step 4: Select Available Time Slot *': 'الخطوة ٤: اختر الموعد المتاح *',
    'Step 5: Confirm & Finalize Details': 'الخطوة ٥: تأكيد الحجز وتعبئة التفاصيل',
    'Appointment Type *': 'نوع الموعد *',
    'Session Mode *': 'نوع الجلسة *',
    'Reason for Visit / Symptoms (Optional)': 'الأعراض أو سبب الزيارة (اختياري)',
    'Confirm & Book Appointment': 'تأكيد وحجز الموعد',
    'NEW PATIENT': 'مريض جديد',
    'FOLLOW UP': 'متابعة',
    'CONSULTATION': 'استشارة',
    'EMERGENCY': 'حالة طارئة',
    'IN CLINIC': 'في العيادة',
    'VIDEO CONSULTATION': 'استشارة مرئية',
    'CHATTING': 'محادثة كتابية'
  }
};
